var n;const r="undefined"==typeof browser;r&&(browser=chrome);const aa=navigator.userAgent.includes("Edg/"),y=navigator.userAgent.includes("Firefox/"),ba=navigator.userAgent.includes("OPR/"),ca=navigator.userAgent.includes("YaBrowser/"),da=Boolean,A=Object.isExtensible,C=Object.values,D=RegExp.prototype.test,ea=RegExp.prototype.exec,fa=Array.isArray,ha=Array.from,ia=Array.prototype.includes;Array.prototype.concat.bind([]);const F=Math.floor,G=Math.random;Function.call.bind(Array.prototype.slice);
const ja=Function.apply.bind(Array.prototype.push);Function.call.bind(Array.prototype.forEach);const ka=Function.apply.bind(String.fromCharCode,null);Function.call.bind(String.prototype.charCodeAt);const la=Function.bind.bind(function(a){return this[a]}),ma=Function.bind.bind(function(a){return a&&a[this]});TextDecoder.prototype.decode.bind(new TextDecoder("ascii"));TextEncoder.prototype.encode.bind(new TextEncoder("utf-8"));D.bind(/^(?:Host|Origin|Referer|Cookie|User-Agent|Connection|DNT|Accept-Encoding|Sec-.+)$/i);
Array.prototype.at||(Array.prototype.at=function(a){0>a&&(a+=this.length);return this[a]});AbortSignal.timeout||(AbortSignal.timeout=function(a){let b=new AbortController;globalThis.setTimeout(b.abort.bind(b),a);return b.signal});function na(a){return ka(a instanceof ArrayBuffer?new Uint8Array(a):a)}function oa(a){return A(a)?a.source.replaceAll("\\/","/"):a}const I={};I[-1]=[2,[111,112],[111]];I[1]=[2,[115,116,117,124,118,119,120,121,127,131,132,123,125,133,126,129,130,134],[115,111,112,113,114]];
I[2]=[2,[114,113,113,115,116,117,118,122,119,125,126,124,121,120,123,112],[111,112,114]];I[3]=[null,[113,114,115,116,117],[112]];I[4]=[2,[111,101,113,112,114,118,119,124,115,116,117,120,121,122,123],[111]];I[5]=[null,[111,112,113],[111]];I[6]=[null,[],[111]];
const pa={16:1,17:2,18:4,45:8,46:16},qa={http:1,https:9,ftp:2,ftps:10,idmreg:12,idmdwnlmfv3:33,idmdwnlmfv4:33,idmdwnlmfv5:33},ra=D.bind(/^(?:https?|socks[45])$/),sa={direct:2,auto_detect:3,system:4,pac_script:5,fixed_servers:7},ta={"text/html":"HTML|HTM","text/css":"CSS","text/javascript":"JS|JSON","text/mspg-legacyinfo":"MSI|MSP","text/plain":"TXT|VTT|SRT|M3U|PLS|M3U8|MPD|F4M|TORRENT|BTT","text/srt":"SRT","text/vtt":"VTT|SRT","text/xml":"XML|MPD|F4M|TTML|TTML2","text/x-javascript":"JS|JSON","text/x-json":"JSON",
"application/dash+xml":"MPD","application/f4m+xml":"F4M|MPD","application/gzip":"GZ","application/javascript":"JS","application/json":"JSON","application/json+protobuf":"JSON","application/msword":"DOC|DOCX|DOT|DOTX","application/ocsp-response":"OCSP","application/octet-stream-m3u8":"M3U8","application/pdf":"PDF","application/pkix-crl":"CRL","application/torrent":"TORRENT|BTT","application/ttaf+xml":"DFXP","application/ttml+xml":"TTML|TTML2","application/vnd.apple.mpegurl":"M3U8","application/vnd.yt-ump":"UMP",
"application/zip":"ZIP","application/x-7z-compressed":"7Z","application/x-aim":"PLJ","application/x-bittorrent":"TORRENT|BTT","application/x-chrome-extension":"CRX","application/x-compress":"Z","application/x-compress-7z":"7Z","application/x-compressed":"ARJ","application/x-dosexec":"EXE","application/x-gtar":"TAR","application/x-gzip":"GZ","application/x-gzip-compressed":"GZ","application/x-javascript":"JS","application/x-mpegurl":"M3U8","application/x-msdos-program":"EXE|DLL","application/x-msi":"MSI",
"application/x-msp":"MSP","application/x-ole-storage":"MSI|MSP","application/x-rar":"RAR","application/x-rar-compressed":"RAR","application/x-sdlc":"EXE|SDLC","application/x-shockwave-flash":"SWF","application/x-silverlight-app":"XAP","application/x-subrip":"SRT","application/x-tar":"TAR","application/x-zip":"ZIP","application/x-zip-compressed":"ZIP","video/3gpp":"3GP|3GPP","video/3gpp2":"3GP|3GPP","video/avi":"AVI","video/f4f":"F4F","video/f4m":"F4M","video/flv":"FLV","video/mp2t":"TS|TSV|M3U8",
"video/mp4":"MP4|M4V|M4S","video/mpeg":"MPG|MPEG","video/mpegurl":"M3U|M3U8","video/mpg4":"MP4|M4V","video/msvideo":"AVI","video/quicktime":"MOV|QT","video/vnd.mpeg.dash.mpd":"MPD","video/webm":"WEBM","video/x-flash-video":"FLV","video/x-flv":"FLV","video/x-mp4":"MP4|M4V","video/x-mpegurl":"M3U|M3U8","video/x-mpg4":"MP4|M4V","video/x-ms-asf":"ASF","video/x-ms-wmv":"WMV","video/x-msvideo":"AVI","audio/3gpp":"3GP|3GPP","audio/3gpp2":"3GP|3GPP","audio/mp2t":"TS|TSA|M3U8","audio/mp3":"MP3","audio/mp4":"M4A|MP4|M4S",
"audio/mp4a-latm":"M4A|MP4","audio/mpeg":"MP3","audio/mpeg4-generic":"M4A|MP4","audio/mpegurl":"M3U|M3U8","audio/webm":"WEBM","audio/wav":"WAV","audio/x-mpeg":"MP3","audio/x-mpegurl":"M3U|M3U8","audio/x-ms-wma":"WMA","audio/x-wav":"WAV","ilm/tm":"MP3","image/avif":"AVIF","image/gif":"GIF|GFA","image/icon":"ICO|CUR","image/jpg":"JPG|JPEG","image/jpeg":"JPG|JPEG","image/png":"PNG|APNG","image/tiff":"TIF|TIFF","image/vnd.microsoft.icon":"ICO|CUR","image/webp":"WEBP","image/x-icon":"ICO|CUR","flv-application/octet-stream":"FLV"};
var ua,va,wa,xa;const K=globalThis,ya=y?69:66,za=y?220:150,Aa=browser.runtime.id,L=browser.runtime.getManifest();var Ba=L.permissions.includes("notifications")||null;
const Ca={16:"images/logo16.png",32:"images/logo32.png"},Da={16:"images/logo16x.png",32:"images/logo32x.png"},Ea=["127.0.0.1:1001","0.1.0.1:1001"],Fa=RegExp("(?!)"),Ga=["main_frame","sub_frame"],Ha=["object","image"],Ia=Ha.concat("xmlhttprequest","media"),N=Ga.concat(Ha,"xmlhttprequest","media","other"),O=["*://*/*"],Ja=["ftp://*/*"],Ka=O.concat(Ja,"file:///*",r?"about:blank":[]),La=O.concat(r?"about:blank":[]),Ma=r&&btoa(G().toString().substr(2,9));browser.runtime.getURL("captured.html?");
const Na=browser.runtime.getURL("welcome.html?")+(Ma?`auth=${Ma}&`:""),Oa=browser.runtime.getURL("").slice(0,-1),Pa=location.href,Qa=ba||ca,Ra=D.bind(/^(?:chrome|about|chrome-extension|chrome-search|ms-browser-extension|ms-appx-web|moz-extension):/),Sa=D.bind(/^(?:application\/(?:json|x-javascript)|text\/(?:javascript|plain))$/),Ta=D.bind(/^(HTM|HTML|CGI|PHP|ASP|ASPX|JSP|JSPX)$/i),Ua=D.bind(/^(MPD|M3U8|F4M)$/i),Va=D.bind(/^ftp:|^idmreg:|\bidman|\binternetdownloadmanager\b/i),Wa=D.bind(/^[GPTSDVACRHX]*$/),
Xa=ea.bind(/^(.*?)(,\s*)?\bapplication\/vnd\.t1c\.(\w+)-([^\s,]+)(?:,\s*)?(.*)$/);ea.bind(/:\/\/.+\/([^/]+?(?:\.([^./]+?))?)(?=[?#]|$)/);const Ya=ea.bind(/\.([^.\\/]*?)(?:\.[0-9.]+)?$/),Za=ea.bind(/^v(\d+)\.(\d+)(?:b(\d+))?\b/),$a=ia.bind([301,302,303,307,308]),ab=ia.bind([301,302,303]),bb=/[:,;]/,cb=/[,;]/,db=D.bind(RegExp("messaging host not found|no such native application|application is not installed","i"));
function eb(a,b,c,e,d,f,g,k){if(a){var h=["MSG#",a,"#",b,"#",c,"#",e];this.j=a;this.type=b;this.v=c;this.flags=e;this.g=d||[];this.m=h;this.C=g;this.B=k;if(d)for(let m of d)h.push(":",m||0);if(f)for(let m in f)if(parseInt(m)&&(g=m,a=f[m],null!=a&&!this.l))switch(b=this.m,c=this.C,d=this.B,e=c&&d,d=d?"/":":",k=a instanceof String?"string":typeof a,b.push(",",g,"="),k){case "string":b.push(fb(a),":",a);break;case "number":b.push(a);break;case "boolean":b.push(a?1:0);break;case "object":if(a instanceof
Array){g=b.length;h=k=0;for(let l of a)l instanceof ArrayBuffer||l instanceof Uint8Array?(c?(l=na(l),k+=l.length):k+=l.byteLength,++h):(l=l.toString(),k+=fb(l)),b.push(l);h&&e?(a=btoa(b.splice(g).join("")),b.push(a.length,"%",a)):b.splice(g,0,k,h?d:":")}else a instanceof ArrayBuffer||a instanceof Uint8Array?e?(a=btoa(na(a)),b.push(a.length,"%",a)):c?(a=na(a),b.push(a.length,":",a)):b.push(a.byteLength,d,a):a instanceof Blob&&b.push(a.size,d,a)}}else this.s=new FileReader}
function gb(){this.g=gb.prototype.A++}gb.prototype.A=1;function hb(a,b,c,e){this.id=a;this.port=b;c&&(this.h=c=c.toLowerCase(),this.ha="iframe"==c);e&&(this.i=e)}hb.prototype.g=0;function P(a,b){return`${a},${b}`}function ib(a,b,c){this.id=P(b,a);this.J=0==a;this.h=null==c||0>c?null:P(b,c)}function jb(){}function kb(a,b,c){a.l?a.h(a):(b.g=c||0,b.h=0,a.s.onload=a.A.bind(a,b),lb(a,b,0,50))}
eb.prototype.A=function(a){for(var b=this.s.result;;)switch(a.h){case 0:var c=b.search(bb);if(0>=c)return this.h(this);var e=b[c],d=b.slice(0,c++).split("#",6);if(5!=d.length||"MSG"!=d[0])return this.h(this);this.j=parseInt(d[1]);this.type=parseInt(d[2]);this.v=parseInt(d[3]);this.flags=parseInt(d[4]);b=b.slice(c);a.g+=c;a.h=":"==e?1:","==e?2:5;break;case 1:c=b.search(cb);if(0>=c)return c?lb(this,a,b.length,100):this.h(this);e=b[c];d=this.g=b.slice(0,c++).split(":");for(var f=0;f<d.length;f++){let g=
d[f];d[f]=g.includes(".")?parseFloat(g):parseInt(g)}b=b.slice(c);a.g+=c;a.h=","==e?2:5;break;case 2:c=b.search(bb);if(0>=c)return c?lb(this,a,b.length,25):this.h(this);e=b[c];f=b.slice(0,c++).split("=",3);if(2!=f.length)return this.h(this);d=parseInt(f[0]);f=parseInt(f[1]);a.g+=c;if(":"==e){a.j=d;a.i=f;a.h=3;b=a;a=a.i;c=b.g;b=b.slice(c,c+a);b.size==a?this.s.readAsText(b):this.h(this);return}this[d]=f;b=b.slice(c);a.h=","==e?2:5;break;case 3:return this[a.j]=b,a.g+=a.i,a.h=4,lb(this,a,0,21);case 4:switch(b[0]){case ",":a.h=
2;b=b.slice(1);break;case ";":a.h=5;break;default:return this.h(this)}a.g++;break;case 5:this.l=!0;this.o(this);a.size>a.g&&(b=new eb,b.o=this.o,b.h=this.h,kb(b,a,a.g));return}};function lb(a,b,c,e){let d=b.g;c=d+c;b.size>c?a.s.readAsBinaryString(b.slice(d,c+e)):a.h(a)}
function Q(){let a=this.constructor.prototype;for(let b in a)b.startsWith("_")||"constructor"==b||(this[b]=a[b].bind(this));this.G=0;this.R=null;this.Oa=this.Ca=0;this.Cb=1;this.H=this.B=null;this.Ua=L.version||"";this.Eb="";this.sa=0;this.za=!1;this.ua=null;this.Y=!1;this.la=this.K=null;this.kb=this.wa=!1;this.N=!y;this.Gb=this.lb=!0;this.mb=this.s=this.O=null;this.Db=this.ya=this.Aa=!1;this.qb=!0;this.Lc=1;this.La=this.v=this.ea=null;this.Ra=1;this.Ib=0;this.jb=this.Ta=null;this.nb=Fa;this.na=[];
this.Ka=0;this.ob=null;this.Sa=this.ta=!1;this.ka=this.A=null;this.Da=Array(16);this.i={};this.m={};this.g={};this.C={};this.h={};this.ma={};this.l={};this.j={};this.Ba={};this.va={};this.o={};this.xa={};this.xa.yc=[];this.hb=[];R(this,!1);browser.action.onClicked.addListener(this.Pb);y&&browser.contextMenus.onShown.addListener(this.rb);y&&browser.runtime.onInstalled.addListener(this.Sb);browser.contextMenus.onClicked.addListener(this.rb);browser.runtime.onMessage.addListener(this.Tb);browser.windows.onCreated.addListener(this.yb);
browser.windows.onRemoved.addListener(this.zb);browser.windows.onFocusChanged.addListener(this.vc);r&&browser.windows.onBoundsChanged.addListener(this.uc);browser.tabs.onActivated.addListener(this.kc);browser.tabs.onUpdated.addListener(this.nc);browser.tabs.onAttached.addListener(this.lc);browser.tabs.onRemoved.addListener(this.mc);mb(this);nb(this)}n=Q.prototype;n.Sb=function(a){this.Ua=a.version=L.version;this.Bc=a};
function ob(a,b){b&&browser.storage.local.set({consent:a.Ua});a.s=null;a.Ma(5);a.N=!0;pb(a)}n.Tb=function(a,b){switch(a[0]){case 38:a[1]&&this.za&&browser.storage.local.set({silent:!0});browser.tabs.remove(b.tab.id);break;case 44:a=new URL(a[1]);a.search.startsWith("?d=")&&this.ja("idmreg:"+a.href.substr(a.protocol.length));break;case 42:ob(this,!0);break;case 43:browser.management.uninstallSelf({showConfirmDialog:!0})}};
n.rb=function(a,b){let c=a.menuItemId;if(null!=c)return qb[c][4].apply(this,arguments);y&&b&&rb(this,b.id,!0,!1,!0)};n.Pb=function(a){if(this.Db){if(this.s)return browser.windows.update(this.s,{focused:!0});var b=a.id,c=this.o[b];R(this,c,b,!0);this.ya&&(c?(this.da(a.windowId),sb(this,b)):tb(this,b))}};function R(a,b,c,e){c?a.o[c]=!b:a.Db=b||e;ub(b,c,e)}
function ub(a,b,c){if(c||!b||!a){var e=a;y&&!b&&(a||c?browser.action.enable():browser.action.disable(),e=!0);c=a?vb+wb:b?xb+wb:c?xb:yb;var d=e?Ca:Da,f=y&&b;browser.action.setTitle({title:a&&f?null:c,tabId:b});browser.action.setIcon({path:e&&f?null:d,tabId:b});a||browser.action.setBadgeBackgroundColor({color:"#606060"});browser.action.setBadgeText({text:a?f?null:"":"X",tabId:b})}}
function pb(a){browser.contextMenus.removeAll();for(let b=1,c=a.i;b<qb.length;b++){let e=qb[b];e[0]&&c[e[1]]&&browser.contextMenus.create({id:b.toString(),title:zb(e[2]),contexts:e[3].split(","),documentUrlPatterns:e[5]||Ka,enabled:!0})}a.ya||(a.ya=!0,R(a,!0),a.I(1,browser.runtime.onConnect,a.fc),r&&a.I(1,browser.proxy.settings.onChange,a.wb),r&&browser.proxy.settings.get({},a.wb),a.I(1,browser.webNavigation.onCreatedNavigationTarget,a.dc),a.I(1,browser.webNavigation.onCommitted,a.vb),a.I(1,browser.webNavigation.onHistoryStateUpdated,
a.Wb),Ab(a,!0),Bb(a,!0),browser.tabs.query({url:O},a.Fa))}
function Bb(a,b){r&&(browser.downloads.setUiOptions||browser.downloads.setShelfEnabled(!b));b?(a.I(3,browser.downloads.onCreated,a.Qb),r&&a.I(3,browser.downloads.onDeterminingFilename,a.Rb),b=r&&!xa?["extraHeaders"]:[],a.I(4,browser.webRequest.onBeforeRequest,a.xb,{urls:Ja,types:Ga}),a.I(4,browser.webRequest.onBeforeRequest,a.xb,{urls:O,types:N},["requestBody"]),a.I(4,browser.webRequest.onBeforeSendHeaders,a.pc,{urls:O,types:N},["requestHeaders"].concat(b)),a.I(4,browser.webRequest.onHeadersReceived,
a.sc,{urls:O,types:N},["responseHeaders"]),a.I(4,browser.webRequest.onResponseStarted,a.tc,{urls:O,types:N}),a.I(4,browser.webRequest.onErrorOccurred,a.rc,{urls:O,types:N}),a.I(4,browser.webRequest.onCompleted,a.qc,{urls:O,types:N}),y&&a.I(4,browser.webRequest.onBeforeRedirect,a.oc,{urls:O,types:Ga})):a.Ma(3,4)}
async function Ab(a,b){let c=await browser.declarativeNetRequest.getSessionRules(),e=[],d=0;if(b&&(b=a.i[17])){a={type:"redirect",redirect:{regexSubstitution:`chrome-extension://${Aa}/captured.html?register=1#\\0`}};for(let f of b.split("|"))b={regexFilter:Cb(f,3),resourceTypes:["main_frame"]},e.push({id:++d,condition:b,action:a})}(e.length||c.length)&&await browser.declarativeNetRequest.updateSessionRules({addRules:e,removeRuleIds:c.map(ma("id"))})}
n.wb=function(a){browser.runtime.lastError;if(a){var b=a.value;a=sa[b.mode];var c,e;this.Da.fill(void 0);if(5==a&&(e=b.pacScript))e.data&&5E4<e.data.length?a=4:(c=e.data)?(a=6,c=c.replace(/\blet\b/g,"var").replace(/,(?=(?:\s*\/\/.*?\n)*\s*[\]}])/g,"")):c=e.url,this.Da.fill(!0);else if(7==a){b=b.rules;e=b.bypassList;c=Db(this,b.singleProxy);if(!c){c=Db(this,b.fallbackProxy);let d=Db(this,b.proxyForHttp,1),f=Db(this,b.proxyForHttps,9);b=Db(this,b.proxyForFtp,2);d!=f||d!=b||d!=c&&c?(c=`${d??""};${f??
""};${b??""};${c??""}`,++a):c=d}e&&e.length&&(c+=";"+e.join(","))}b=5>a?a.toString():c?`${a}:${c}`:null;b!=this.A&&(this.A&&Eb(),this.A=b)}};function Db(a,b,c){if(b){let e=b.scheme||"http",d="https"==e;a=a.Da;c?a[c]=d:a.fill(d);if(ra(e))return`${e}://${b.host}${b.port?":":""}${b.port||""}`}}
function Fb(a,b,c,e){if(b){var d=b.type;if("direct"==d)return"0";"socks"==d&&(d="socks5");if(ra(d)){var f=`1:${d}://${b.host}:${b.port}`;"socks5"==d&&b.proxyDNS&&(f+="#");c||e||!(c=a.ka)||(c=c.substr(c.indexOf(";")+1||c.length));c&&(f+=`;${c}`);e&&f&&(a.ka=f);return f}}}async function Eb(){}n.Ja=function(a,b,c,e){let d=this.l;return b in d?d[b]:d[b]=new hb(b,a,c,e)};function Gb(a,b){a=a.j;let c=b.id;a[c]!==b&&(a[c]=b);y&&b.ra&&(a[b.ra]=b)}
function Hb(a,b,c,e,d){let f,g,k;A(b)?(f=b.frameId??0,g=b.parentFrameId,k=b.method&&b.id,c||=b.tabId,d||=b.url):f=b;let h=a.C[P(c,f)];h||(h=new ib(f,c,g),a.C[h.id]=h);k?(h.i!=k&&(h.i=k,h.o=d,h.M=!1,h.g&&(h.g=d.startsWith(b.initiator||b.originUrl))),h.s="POST"==b.method):d&&(d.startsWith("about:blank")?f&&(h.g=!0):h.u=d);null!=e&&(h.refresh=e);return h}function Ib(a,b){return a.C[P(b.tabId,b.frameId)]}function Jb(a){let b=new gb;return a.ma[b.g]=b}
function Kb(a,b){let c;b instanceof gb?c=b.g:b=a.ma[c=b];delete a.ma[c];return b}function Nb(a,b){for(let c of a.na)if(c&&c[101].test(b))return c.V;return 0}
n.Na=function(){var a=this.Ca%(Ea.length+1);a<Ea.length?(a=this.R=new WebSocket(`ws://${Ea[a]}/?cid=${this.ua||0}&rnd=${G().toString().substr(2,9)}`,"plugin.v3.internetdownloadmanager.com"),a.onerror=Ob,a.onopen=this.ab,a.onclose=this.ia,a.onmessage=this.jc,1==a.readyState?this.ab(1):3==a.readyState?this.ia():this.B=K.setTimeout(this.ia,1500,a)):(a=this.R=browser.runtime.connectNative("com.tonec.idm"),a.onDisconnect.addListener(this.ia),a.onMessage.addListener(this.Xb),this.B=K.setTimeout(this.ab,
0,2))};n.ab=function(a){this.B&&(K.clearTimeout(this.B),this.B=null);this.G=A(a)?1:a;this.Cb=1;this.za=!1;var b=browser.i18n.getUILanguage().replace("_","-");"sr"==b&&(b+="-Cyrl-CS");a=[109,80,Qa?1028:1031,0,16845059,this.ua,15,L.manifest_version];b={[112]:va,[113]:ua,[125]:JSON.stringify(this.Bc),[116]:b};S(this,2,5,Qa?0:1024,a,b)};
n.ia=function(a){this.B&&(K.clearTimeout(this.B),this.B=null);this.H&&(K.clearTimeout(this.H),this.H=null);var b=browser.runtime.lastError||a&&a.error,c=this.R;if(c instanceof WebSocket){if(a===c)return c.close()}else c&&db(b&&b.message)&&(this.za=!0);this.R=null;this.G&&(this.G=0,this.Ba={},Bb(this,!1),Ab(this,!1),this.Ma(1,2),this.ya=!1,this.A=this.jb=null,R(this,!1));a=++this.Ca;b=Ea.length+1;c=a/b;120>c&&(1==c&&Pb(this),!a||a%b?this.Na():K.setTimeout(this.Na,5E3*c))};
n.tb=function(){let a=this.R;a instanceof WebSocket?a.close():a&&(a.disconnect(),this.ia())};n.$a=function(a){if(this.H)a?(this.H=null,S(this,0,1,1)):K.clearTimeout(this.H);else if(a)return;this.H=K.setTimeout(this.$a,15E3,!0)};n.jc=function(a){let b=new eb;b.o=this.ub;b.h=this.tb;kb(b,a.data)};n.Xb=function(a){let b=new eb;b.o=this.ub;b.h=this.tb;kb(b,new Blob([a]))};
function S(a,b,c,e,d,f){let g=a.Oa;var k=a.G;if(!k)return 0;let h=a.Cb++;b=new eb(h,b,c,e,d,f,2==k,99<=g);if(1==k){k=a.R;var m=k.send;b.l||(b.m.push(";"),b.l=!0);m.call(k,new Blob(b.m))}else try{m=a.R;var l=m.postMessage;b.l||(b.m.push(";"),b.l=!0);l.call(m,b.m.join(""))}catch(q){return a.ia(),0}e&1&&(a.Ba[h]=b);a.H&&a.$a();return h}
function Qb(a,b){if(b.g){var c=b.g[1],e=a.j[c];if(e)return e.Z?b.i=e.port.id:null;e=a.m;for(var d in e)if(e[d].i==c)return b.i=d}c=b[6];d=b[17];e=b[50];let f=b[7];var g=a.xa;let k=a.l;a=a.g;let h,m,l;if((h=g[c])||(h=g[d]))return b.i=h.id;if(h=g[e])l=h.id;for(let q in k){g=k[q];let p=g.i;if(p){if(p==c||p==d||p==e){h=g.port;if(f){let t=a[h.tabId];t&&t.u!=f&&(h=null)}if(h)return b.i=h.id}p==f&&(m=g.port.id)}}return l?b.i=l:m?b.i=m:null}
function Rb(a,b){let c=b.i;if(c)return c;if(b.g){var e=a.g[P(b.g[6],b.g[7])];e?c=e.id:(e=b.g[7])&&a.m[e]&&(c=e)}if(c||=Qb(a,b))return b.i=c;e=a.m;let d=b[50],f=b[7];for(let g in e){let k=e[g];if(k.u==d)return b.i=k.id;k.u==f&&(c=k.id)}return c?b.i=c:f?browser.tabs.query({url:f}).then(g=>g?.length&&(g=a.g[g[0].id])?b.i=g.id:null,()=>null):null}
async function Sb(a,b){var c=b.tabId;let e=b.$;if(0<e&&!b.h){var d=await browser.webNavigation.getFrame({frameId:e,tabId:c});d&&(d=d.parentFrameId,0<=d&&(b.h=P(c,d)))}if(null!=e&&b.l){if(d=a.C[P(c,e)]){b.i=d.i;b.M|=d.M;b.refresh|=d.refresh;b.o=d.g;let f=d.aa;f&&b.u!=f&&(b.aa=f);b.h||(b.h=d.h);(d=a.j[b.i])&&!d.port&&(d.port=b)}a.g[P(c,e)]=b;d=b.V;c=[11,a.Oa,b.id,c,e,d,b.refresh,b.M,a.i[22],a.i[23],a.kb?"debug.js":null];d&&b.M&&(a=a.na[d],c.push("document.js"),ja(c,a.Kb.map(la(a)).map(oa)));b.postMessage(c)}}
n.ja=async function(a,b,c,e,d,f){var g=T(a);if(g){var k=0<(g&32),h=1==(g&=7),m;h&&!k&&(m=await U(a));g=[g];a={[6]:Tb(a,h&&this.Y),[50]:b,[7]:c,[8]:e,[100]:d,[102]:f,[51]:V(m),[54]:navigator.userAgent,[121]:y?this.ka:this.A};S(this,14,1,0,g,a)}};
async function Ub(a,b,c){if(b&&b.length){var e=b.map(h=>U(h[0]));if(c){var d=c.i;var f=c.ea;var g=c.o;d&&!f&&e.push(U(d))}e.length&&(e=await Promise.all(e),b.forEach(h=>h[5]=V(e.shift())),e.length&&(f=V(e.shift())));c=0;var k=[0,0,0];d={[8]:4,[54]:navigator.userAgent,[7]:d,[110]:g,[111]:f,[121]:y?a.ka:a.A};1<b.length&&(k[1]=S(a,15,1,0,[b.length],d),c=16,d={});for(let h of b)k[2]++,d[6]=h[0],d[100]=h[2],d[102]=h[3],d[50]=h[4],d[51]=h[5],S(a,14,2,c,k,d)}}
n.Qa=function(a,b){if(!this.G)return Vb(b.id,"cannot_contact_idm");let c=a.linkUrl,e=a.pageUrl,d=e,f=this.g[P(b.id,a.frameId)];if(5==a.menuItemId)return browser.downloads.search({query:[c]},this.Lb.bind(this,c));if(2==a.menuItemId){if(c=a.frameUrl,c&&"about:blank"!=c||(c=e,d=null),this.K&&f?.V)return Wb(this,!0)}else if(!c){c=a.srcUrl;if(!T(c)){if(this.K&&f?.V&&"video"==a.mediaType)return Wb(this,!0);return}if(f&&c)return a=Jb(this),a.tabId=b.id,a.port=f,a.m=c,a.s=d,a.i=e,a.flags=4,f.postMessage([18,
a.g,c])}this.ja(c,d,e,4)};n.ib=function(a,b){if(!this.G)return Vb(b.id,"cannot_contact_idm");rb(this,b.id,3==a.menuItemId)};n.Lb=function(a,b){let c,e,d;for(;c=b.pop();)c.exists&&"complete"==c.state?e||d||(d=c.referrer):(e||=c.referrer,browser.downloads.erase({id:c.id}));this.ja(a,e||d,null,4)};
function rb(a,b,c,e,d,f,g,k,h){if(!e||a.i[-5]){var m=a.g[b];if(m){var l=Jb(a);l.tabId=b;l.port=m;l.Y=c;l.K=d;l.h=0;l.j=[];if(m=e&&!!f)l.N=!0,l.R=f,l.B=g,l.C=k,l.v=h,f.J||Xb(a,f);f=l.g;(e=e&&a.i[12])?(e=e.replace(/\./g,"\\.").replace(/\*/g,".*").replace(/~/g,"(?:.*\\.)?"),e="^(?:http|https|ftp|ftps)://(?:[^\\/]*@)?(?:"+e+")(?::\\d+)?(?:\\W|$)"):e="^(?:http|https|ftp|ftps)://";l.l=Yb(a,b,[12,f,c,m||d,e]);l.G=0;l.l||Kb(a,l)}}}
n.xc=function(a,b,c,e,d,f,g,k){if(a=this.ma[b]){e&&(a.h+=e);g&&(a.i=g);k&&(a.o=k);if(d&&("string"==typeof d&&(d=JSON.parse(d)),d instanceof Array)){if(f)for(let h of d)h[4]=f;ja(a.j,d)}++a.G<a.l||(a.N?(e=a.tabId,(d=this.h[a.port.g])&&d.D==e&&a.h&&(f=a.v,g=d.h,k=d.i,S(this,10,1,0,[4294967295,d.A,Math.round(a.B*f+(d.l+g)*k),Math.round(a.C*f+(d.K+g)*k),0,a.h]),this.v=e,Yb(this,e,[13,!0]))):a.K?(e=0<a.h,this.qb!=e&&(this.qb=e,browser.contextMenus.update(3,{visible:e}),browser.contextMenus.refresh())):
(e=a.j,e.length?Ub(this,e,a):Vb(a.tabId,"cannot_find_links")),Kb(this,a))}};n.bc=function(a,b,c,e){(a=Kb(this,b))&&this.ja(a.m,a.s,a.i,a.flags,c,e)};n.Qb=function(a){if(!this.Sa&&this.i[-6]){var b=a.finalUrl||a.url;if(T(b,!0)){var c=a.id,e=Date.parse(a.startTime),d;for(d of C(this.j))if(b==d.url&&e>=d.Fb&&50>e-d.Fb)break;if(d&&(d.Pa=c,a.request=d,this.o[d.tabId]))return;this.va[c]=a;browser.downloads.pause(c,Ob)}}};
n.Rb=function(a,b){var c=a.id;let e=this.va;var d=e[c];if(d){var f=this.i,g=d.request;d=a.finalUrl||(a.finalUrl=a.url);var k=g?g.Ia:new URL(d),h=g?g.U:a.U=T(d,!0),m=g?g.fa:a.fa=W(a.filename||k.pathname);if(!((g?g.ta:a.ga=this.ta)||this.wa||f[1].test(m)&&!f[9].test(k.hostname)&&!f[19].test(k.href)))return Zb(this,c);a.request=g;a.Ac=b;e[c]=a;if(g)return X(this,2,g,a)?a.Va=!0:Zb(this,c);if(1==h){if(!a.referrer){b=this.h;for(var l of C(this.m))if(l.u==d&&(a.referrer=l.v,(c=b[l.g])&&c.D==l.tabId))break}l=
U(d);d=d==a.url?null:U(a.url);Promise.all([l,d]).then(q=>$b(this,a,...q));return a.Va=!0}return $b(this,a)}};function $b(a,b,c,e){var d=Date.parse(b.startTime)||Date.now();d=[b.id,0,F(d),0,b.U,2];c={[6]:Tb(b.finalUrl,a.Y),[4]:b.fa,[103]:b.totalBytes||null,[100]:b.filename||null,[127]:b.mime||null,[8]:b.ga?2048:0,[50]:b.referrer||null,[51]:V(c),[54]:navigator.userAgent,[122]:a.A};b.finalUrl!=b.url&&(c[17]=Tb(b.url),c[56]=V(e));return!!S(a,13,1,129,d,c)||Zb(a,b.id)}
function Zb(a,b,c){let e=a.va[b];if(e){delete a.va[b];let d=e.request;d&&(d.Pa=null,d.Ya&&a.L(d));if(c)return browser.downloads.cancel(b,Ob),!0;e.Va&&(e.Va=!1,e.Ac());browser.downloads.resume(b,Ob)}}n.ec=function(a,b,c,e,d,f){this.Ja(a,b,c,e);S(this,23,2,0,[b,a.tabId,a.i,a.V,a.$],{[132]:e,[133]:d,[134]:f})};
n.W=function(a,b,c){if(4294967295==a)this.v=null,c=!0;else{let e=this.l[a];if(e){c=e.g;if(!c)return;if(b)switch(c){case 3:return;case 2:break;default:e.g=3;K.setTimeout(this.W,1E3,a,!1,!0);return}e.g=0;c=!0}}c&&S(this,8,1,32,[a])};
n.Fc=async function(a,b,c,e,d,f,g,k,h,m){let l=a.tabId,q=a.g;var p=this.h[q];let t=this.o[l];if(b){var u=Kb(this,b);if(u=u&&u.H){if(!c&&a.o){let H=this.g[a.h];if(H)return H.postMessage([15,b,null,u[6],u[17],u[50],u[31],u[133],u[134]])}var v;b={};if(!e){if(!c||null==d){if(!a.J){c=a.oa;f="iframe";g=a.u;var w=!!c}if(!w){c=l;f=g=null;var x=!0}}a=this.Ja(a,c,f,g);p=l==p.D&&!p.S&&(x||w||d)&&!t;!p||x||a.g||K.setTimeout(this.da,3E3,q);var E=2;a.g=p?1:2;var J=(p?128:64)|(x?512:0);!k&&(v=this.g[l])&&(k=v.s)}k&&
(b[101]=k,b[128]=h);m&&(b[137]=m);await ac(this,u,E||1,J||0,q,l,c,b);!E||x||t||bc(this,c,d)}}else e?(this.W(c,!0),delete this.l[c]):l!=p.D||p.S||t||(d?bc(this,c,d,!0):cc(this,c))};function dc(a,b){let c=a.h[b];if(c&&c.g){var e=c.h,d=c.i;S(a,7,2,c.S?128:c.B?256:c.j?512:0,[b,Math.round((c.l+e)*d),Math.round((c.K+e)*d),Math.round((c.width-e-c.C)*d),Math.round((c.height-e)*d)])}}
function bc(a,b,c,e){let d=a.l[b];if(d&&d.g){var f=d.port;let g,k=256;2==d.g&&(null==e&&(g=a.h[f.g])&&(e=f.tabId==g.D&&!g.S),e?(k|=128,d.g=1):k|=64);(e=d.ha)&&!c&&(c=f.j);let h,m,l,q,p,t;if(c){h=c[0];m=c[1];l=c[2]||h+1;q=c[3]||m+1;p=c[4];if(c=!e&&f.j)h+=c[0],m+=c[1],l=Math.min(l+c[0],c[2]),q=Math.min(q+c[1],c[3]);if(f=a.g[f.tabId])t=f.G}S(a,9,1,k,[b,h,m,l,q,p,t])}}
n.da=function(a){var b=this.o;let c=this.g;var e=this.h;let d=a?[e[a]]:C(e);a=[];e={};for(var f of d)!f||f.S||f.ca||b[f.D]||a.push(f.D);if(a.length)for(let g of C(this.l))g.g&&(b=g.port,f=b.tabId,a.includes(f)&&((f=b.J?b:c[f])&&f.update&&(f.update=!1,f.postMessage([14,!1])),g.h?b.J?b.postMessage([15,null,g.id]):Xb(this,b,null,e):bc(this,g.id,null,!0)))};function ec(a,b){let c=a.h,e;if(b=null==b?C(c):(e=c[b])?[e]:null)for(e of b)tb(a,e.D)}
function tb(a,b,c,e){e=0!=e;let d=c?0:2;c=c?32:64;for(let f of C(a.l))f.g&&f.port.tabId==b&&f.g!=d&&(e||f.h)&&(f.g=d,S(a,8,1,c,[f.id]))}function cc(a,b){let c=a.l[b];c&&1==c.g&&(c.g=2,S(a,8,1,64,[b]))}function fc(a,b,c,e){var d=a.Ka;let f=(d&b)!=((c?255:128)&b);a.Ka=c?d|=b:d&=~b;f&&(c=a.i[-32],b=a.i[-33],c=a.ta=0!=c&&(d&c)==c,d=a.Sa=0!=b&&(d&b)==b,a.ob=(c||d)&&e||null)}
n.fb=function(a,b,c,e,d){let f=this.h[a];if(f)if(f.ca?e&&(K.clearTimeout(f.ca),f.ca=null):e||=-1,0<=e)f.o|=b,f.s|=c,e&&(f.ca=K.setTimeout(this.fb,e,a));else{b|=f.o;c|=f.s;f.o=f.s=f.ca=null;if(b){for(let g of C(this.m))g.J&&g.g==a&&(g.update=!0);d?this.P(d):browser.windows.get(a,this.P);browser.tabs.query({windowId:a,active:!0},this.P)}if(c){if((a=this.h[a])&&!a.S&&!a.ca&&(a=a.D,!this.o[a])){b=this.l;for(let g in b)c=b[g],c.g&&c.port.tabId==a&&1==c.g&&S(this,8,1,1152,[g])}}else this.da(a)}};
n.P=function(a,b){browser.runtime.lastError;a instanceof Array&&(a=a.shift());if(a){var c=a.windowId||a.id,e=this.h[c];if(e){var d=!a.windowId;if(d){b&&(e.i=this.Ra);var f=e.j="minimized"==a.state,g=e.B="maximized"==a.state;f||(e.width=a.width,e.height=a.height,e.m=a.left,e.v=a.top,f=e.S,a=e.S="fullscreen"==a.state,g=g&&-e.m,0<g&&16>=g&&g==-e.v&&(e.h=g),a==f||b||(a?ec(this,c):this.da(c)))}else{if(e.N&&Ra(a.url))return;a.active&&(e.D=a.id);a.width&&(e.H=a.width);a.height&&(e.G=a.height)}if(!e.j){a=
e.width;let k=e.H;g=e.height;f=e.G;let h=!y&&(k>a||f>g);if(h||!k||!f){d||h&&browser.windows.get(c,this.P);return}d=a-k;a=d/2;0<=a&&16>=a?(e.h=a,e.l=e.C=0):(a=e.h,y||ba?e.l=d-2*a:e.C=d-2*a);d=g-f-2*a;d>=(e.R?20:50)&&d<=za&&(e.K=d);e.N=!0}b||dc(this,c);return e}}};function sb(a,b){return a.o[b]?!0:(a=a.g[b])&&a.refresh?(a.refresh=!1,browser.tabs.reload(b),!0):!1}
n.Cc=function(a,b,c,e){a.u=b;a.v=c;a.refresh&&!e&&(a.refresh=!1);null==a.$&&Sb(this,a);this.da(a.g);0<this.K&&a.J&&1==a.V&&(this.i[11]?.test((new URL(b)).hostname)||Wb(this))};n.Ec=function(a,b,c,e,d){a.s=b;a.G=d;a=[a.i,a.tabId,a.g,e,d];e={};e[110]=b;e[128]=c;S(this,21,1,0,a,e)};
n.Gc=function(a,b,c,e,d){let f=a.tabId,g=this.g[P(f,c)];if(g){var k=g.j;g.oa=e;if(g.j=d){var h=a.j;h&&(d[0]+=h[0],d[1]+=h[1],d[2]=Math.min(d[2]+h[0],h[2]),d[3]=Math.min(d[3]+h[1],h[3]));if(k&&k.join()!=d.join()){k=this.g;a=P(a.tabId,"");c=a+c;for(let m in k)m.startsWith(a)&&(h=k[m],h.h==c&&g.postMessage([16,b,h.$,h.oa]))}}if(!this.o[f]){bc(this,e,d);for(let m of C(this.l))m.port==g&&m.g&&m.h&&!m.ha&&g.postMessage([15,null,m.id])}}};
function Xb(a,b,c,e){var d=a.g;c=[16,c];a=[b];for(let f;f=d[b.h];b=f){if(e)if(e[b.id])break;else e[b.id]=!0;a.push(f)}for(e=a.pop();b=a.pop();e=b)d=b.oa,c[2]=b.$,c[3]=d,c[4]=d?null:b.u,c[5]=d?null:b.aa,e.postMessage(c)}function Yb(a,b,c){a=a.g;b=P(b,"");let e=0;for(let d in a)d.startsWith(b)&&(a[d].postMessage(c),e++);return e}
n.Fa=function(a,b){let c={},e={files:["content.js"],target:c,injectImmediately:!0};b?c.frameIds=[b]:c.allFrames=!0;if(a instanceof Array)for(;b=a.shift();)b.discarded||(c.tabId=b.id,browser.scripting.executeScript(e).catch(()=>null));else if(b=a)c.tabId=b.id||b,browser.scripting.executeScript(e).catch(()=>null)};function gc(a,b,c,e){null==c&&(c=b.A==a.ea);S(a,6,2,17|(c?2048:1024)|(b.B?256:b.j?512:0),[b.A,b.g,b.width,b.height,b.m,b.v,b.i],{[117]:e})}
async function nb(a){var b=browser.windows.getAll({windowTypes:["normal","popup","app"]}),c=browser.tabs.query({active:!0});[b,c]=await Promise.all([b,c]);let e={};if(c)for(let d of c)e[d.windowId]=d;for(let d of b)b=e[d.id],c=a.P(d,!0)||a.yb(d,!0,b),gc(a,c,d.focused,d.title||b&&b.title)}async function hc(a){await ic("system.display")&&(a.Ib=(await browser.system.display.getInfo(null))[0].displayZoomFactor)}
n.fc=function(a){let b=a.sender.tab;if(b&&!(0>b.id)){a.name=a.name.split(":").shift();var c=a.id;null==c&&(c=a.id=this.Lc++);var e=b.id,d="top"==a.name;a.tabId=e;a.g=0>b.index?null:b.windowId;a.l=!0;a.m=!1;a.update=d;a.J=d;a.$=d?0:a.sender.frameId;a.H=0;a.u=a.sender.url||d&&b.url||null;a.aa=null;this.m[c]=a;d&&(this.g[e]=a);a.u&&(a.V=Nb(this,(new URL(a.u)).hostname));a.onMessage.addListener(this.hc.bind(this,a));a.onDisconnect.addListener(this.Ga);Sb(this,a)}};
n.Ga=function(a){browser.runtime.lastError;if(a.l){a.l=!1;var b=P(a.tabId,a.$),c=this.ma,e=this.l,d,f=this.xa,g=this.j,k;for(let h in c)c[h].port===a&&delete c[h];for(let h in e)if(d=e[h],d.port===a)this.W(h),delete e[h];for(let h in f)f[h]===a&&delete f[h];for(let h in g)(k=g[h],k.port!==a||k.M)||delete g[h];this.ob===a&&fc(this,255,!1);delete this.m[a.id];delete this.g[b];a.J&&delete this.g[a.tabId];a=this.C;for(let h in a)b==a[h].h&&delete a[h]}};
n.hc=function(a,b){let c=b.shift();b.unshift(a);switch(c){case 21:this.Cc.apply(this,b);break;case 24:this.Ec.apply(this,b);break;case 22:this.Gc.apply(this,b);break;case 23:this.Fc.apply(this,b);break;case 41:this.ec.apply(this,b);break;case 25:this.Ja.apply(this,b);break;case 26:rb(this,a.tabId,!0,!0,!1,a,b[1],b[2],b[3]);break;case 27:this.xc.apply(this,b);break;case 28:this.W(4294967295);break;case 29:this.sb.apply(this,b);break;case 30:this.sb.apply(this,b);break;case 31:this.$b.apply(this,b);
break;case 32:this.cc.apply(this,b);break;case 39:this.ac.apply(this,b);break;case 33:this.Vb.apply(this,b);break;case 34:this.Zb.apply(this,b);break;case 35:this.bc.apply(this,b);break;case 36:this.wc.apply(this,b);break;case 37:this.ic.apply(this,b);break;case 45:this.Ub.apply(this,b)}};
n.ub=function(a){let b=a.type;var c=a.v,e=a.flags,d=a.g,f;if(1==b){let l=d[0];if(f=this.Ba[l])b=f.type,delete this.Ba[l]}switch(b){case 3:0<=this.Ca&&(this.Ca=-1,Eb());var g=d[0],k=d[5],h=d[6],m=d[4];d=d[8];this.Oa=g;jc(this,h);kc(this,k,a);lc(this);if(m||d)d=(m?m/96:1)*(d?d/100:1),this.Ra=r&&1.245>d?1:d,nb(this),r&&this.Ib&&hc(this);97>g&&this.$a();Pb(this);break;case 4:g=this.i;this.wa=!!(d[3]&2147483648);this.kb=!!(d[3]&1073741824);kc(this,d[2],a);lc(this);e&2048&&(K.idm=this);g[-6]=0<(e&64);g[-10]=
0<(e&1024)||Qa;g[-5]=0<(e&32);g[-1]=0<(e&2);g[-8]=0<(e&256)||2>c;g[-9]=0<(e&512)||2>c;g[-32]=d[0];g[-33]=d[1];g[12]=a[12];g[17]=a[17];Y(g,a,1);Y(g,a,2);Y(g,a,3);Y(g,a,4);Y(g,a,10);Y(g,a,9,2);Y(g,a,11,2);Y(g,a,20);Y(g,a,21,1);mc(g,a,19);mc(g,a,18,1,1);(this.N||this.lb)&&pb(this);break;case 18:f=d[0];d=d[1];e=I[d?-d:f];if(!e)break;d=this.na[f]={};c=e[2];d.V=f;d.Nc=e[0];d.Kb=e[1];for(g in a)(g=parseInt(g))&&(102==g||110<g&&150>g)&&(d[g]=c.includes(g)?RegExp(a[g]):a[g]);for(k of c)(h=d)[m=k]||(h[m]=Fa);
g=this.na.map(ma(102)).filter(da);this.nb=RegExp("^https?://(?:"+g.join("|")+")","i");Y(d,a,101,2);break;case 5:nc(this,d[0],e,d[1]);break;case 6:if(e&4)break;nc(this,f.g[0],e,d[2],d[1]);break;case 8:a=d[0];d=e&32;if(4294967295==a)Yb(this,this.v,[13,!1]),this.v=null;else if(a=this.l[a])a.g=d?0:2;break;case 11:4294967295==d[0]&&(rb(this,this.v,!0,!0),this.v=null);break;case 12:try{let l=a.g[5];d=4==l?2:3;if(1==l||2==l){if(Qb(this,a)){let q=a[4];if(this.i[3].test(q))1==l?d=6:l=4;else if(this.i[-1]||
this.i[4].test(q))d=6;a[8]|=256}if(3==d){let q=this.h[this.ea];q&&this.o[q.D]&&(d=1)}}if(4!=l)ac(this,a,d);else{switch(a.g[4]){case 1:a[7]||(a[7]=a[50]);break;case 3:a[7]||(a[7]=a[32]),a[50]||(a[50]=a[31])}oc(this,a)}}catch(l){ac(this,a,0)}break;case 13:a=f.g[0];g=f.g[5];d=d[1];k=3==d;if(3>=g)f.flags&128?Zb(this,a,k):this.L(a,k);else if(5==g)if(d){if(f=(m=this.j[a])&&m.pa)d=m.url,g=m.method,k=m.requestHeaders,(h=m.ba)&&((h=pc(h,k,!0))??(g="GET")),m.port.postMessage([19,a,f,d,g,k,h])}else qc(this,
a);break;case 20:d=a[123];g=!d;a=[a.j];k={};y&&(h=this.ka)&&(k[122]=h,d&&(g=h.substr(2).split(";",1).shift()==d));k[121]=this.A;S(this,1,2,g?2:4,a,k);break;case 24:rc(this,a);break;case 22:sc(d[0],d[1],a[131],a[130]);break;case 100:e&1&&S(this,100,1,0,[a.j],a);break;default:e&1&&S(this,1,2,0,[a.j])}};
async function sc(a,b,c,e){null==Ba&&(Ba=await ic("notifications")||!1);Ba&&(browser.notifications.create(a.toString(),{type:"basic",title:e??"",message:c,iconUrl:"images/logo48.png"}),b&&K.setTimeout(browser.notifications.clear,1E3*b,a.toString()))}async function rc(a,b){let c=await U(b[6],!!(b.flags&16));b=[b.j,c?c.length:0];let e={[51]:V(c)};S(a,1,2,c?2:4,b,e)}
async function oc(a,b){try{let g,k=b.i||b.g[2],h=b.g[8],m=a.l[h];if(m&&m.port)g=m.port;else if(k in a.m)g=a.m[k];else if(k=await Rb(a,b))g=a.m[k];else{let l=await browser.windows.getLastFocused();if(l){let q=a.h[l.id];q&&(g=a.g[q.D])}}if(g){b.i=g.id;var c=a.h[g.g];if(c&&c.g){var e=a.g[g.tabId];e&&e.update&&(e.update=!1,e.postMessage([14,!0]));var d=Jb(a),f=[15,d.g,h];d.H=b;h||f.push(b[6],b[17],b[50],b[31],b[133],b[134]);g.J||Xb(a,g,d.g);g.postMessage(f)}else ac(a,b,1)}else ac(a,b,0)}catch(g){ac(a,
b,0)}}async function ac(a,b,c,e,d,f,g,k){-1!=c&&(e|=0==c?4:2,k||={},k[8]=b[8],d=[b.j,c,d,g,f,-1],b.flags&32&&(3==c||2==c)&&(b=await U(b[6],!!(b.flags&16)))&&(d[5]=b.length,k[51]=V(b)),S(a,1,2,e,d,k))}n.dc=function(a){Hb(this,a).j=!0;y&&browser.windows.get(a.windowId,this.P)};
n.vb=function(a,b){var c=a.tabId,e=a.frameId;let d=a.url;var f=a.transitionType,g=a.frameType,k=a.documentId;let h="prerender"==a.documentLifecycle;this.O!=c||Ra(d)||(this.O=null);e&&h&&"outermost_frame"==g&&(e=a.frameId=0);f=f&&f.endsWith("_subframe");var m=!0;if(g=this.C[P(c,e)]){m=g.l;g.l=h?k:null;if(m&&m==k)return;k=g.m;m=!(d&&k&&(new URL(d)).hostname==(new URL(k)).hostname);g.m=d}else h&&(g=Hb(this,a),g.l=k);!f&&this.o[c]&&R(this,m,c);if(k=this.g[P(c,e)])if(this.v&&(a=this.h[k.g])&&a.D==this.v&&
this.W(4294967295),b){a:{b=k.u;c=new URL(b);e=new URL(d);if(c.origin==e.origin&&c.pathname==e.pathname)switch(Nb(this,c.hostname)){case 1:if("/watch"==c.pathname&&c.searchParams.get("v")==e.searchParams.get("v")){b=!0;break a}break;case 4:if((c.pathname.startsWith("/p/")||c.pathname.startsWith("/reel/"))&&c.searchParams.get("img_index")==e.searchParams.get("img_index")){b=!0;break a}}b=d==b}if(!b){b=this.l;var l;for(let q in b)if(l=b[q],l.port===k)2==k.V||4==k.V?cc(this,q):(this.W(q),delete b[q]);
k.H++;k.u=d;k.J&&(k.update=!0);k.postMessage([17,!0])}}else this.Ga(k,!0),f&&"about:blank"==k.u&&this.Fa(c,e);else f&&"about:blank"==d?(Hb(this,a),this.Fa(c,e)):g&&g.j&&(g.u||!b)?g.j=!1:y&&browser.tabs.get(c,this.P)};n.Wb=function(a){return this.vb(a,!0)};
n.yb=function(a,b,c){let e=a.id;c={A:e,width:a.width,height:a.height,m:a.left,v:a.top,i:this.Ra,h:8,K:ya,l:0,C:0,R:"popup"==a.type||"app"==a.type,S:"fullscreen"==a.state,B:"maximized"==a.state,j:"minimized"==a.state,D:c&&c.id,G:c&&c.height,H:c&&c.width,N:!y,g:null,ca:null};Object.setPrototypeOf(c,jb.prototype);this.h[e]=c;a.focused&&(this.ea=e);b?(browser.tabs.query({windowId:e,active:!0},this.P),browser.tabs.query({windowId:e,url:O},this.Dc),browser.tabs.query({windowId:e,url:O},this.Fa)):y&&this.Ta==
e&&(this.Ta=null,browser.tabs.query({windowId:e,active:!0},this.P));return c};n.Dc=function(a){for(let b of a)Hb(this,0,b.id,!0,b.url)};n.zb=function(a){S(this,5,1,32,[a]);delete this.h[a];this.s==a&&ob(this)};n.vc=function(a){if(0<a){this.s&&browser.windows.update(this.s,{drawAttention:!0});let b=this.h[a];b&&(this.ea=a,b.g||gc(this,b,!0),browser.windows.onBoundsChanged||browser.windows.get(a,this.P),sb(this,b.D))}else this.ea=null};n.uc=function(a){this.fb(a.id,!0,!1,-1,a)};
function nc(a,b,c,e,d){let f=a.h[b];f?(e&&(f.i=e),d&&(f.g=d),e=!!(c&128),f.S!=e&&(f.S=e)&&ec(a,b),(d||c&4096)&&dc(a,b)):a.zb(b)}n.nc=function(a,b,c){let e=c.active;c=c.windowId;let d=e&&this.h[c];d&&(d.g||gc(this,d));"complete"==b.status&&(a=this.g[a])&&!a.m&&(a.m=!0,e&&this.da(c))};n.mc=function(a){let b=this.g,c=this.C,e=P(a,"");this.O==a&&(this.O=null);let d=b[a];d&&this.Ga(d,!0);for(let f in b)f.startsWith(e)&&this.Ga(b[f],!0);for(let f in c)f.startsWith(e)&&delete c[f];delete this.o[a]};
n.kc=function(a){let b=a.tabId;a=a.windowId;this.Ka=0;this.v&&this.W(4294967295);var c=this.h[a];c?(tb(this,c.D),c.D=b,(c=this.O)&&b!=c&&(this.s?browser.windows.update(this.s,{drawAttention:!0}):this.G&&this.N&&(this.O=null,K.setTimeout(browser.tabs.remove,250,c))),browser.tabs.get(b,this.P),sb(this,b)||this.da(a)):y&&(this.Ta=a)};n.lc=function(a,b){b=b.newWindowId;for(let c of C(this.m))c.tabId==a&&(c.g=b);tb(this,a,!0)};n.Yb=function(a){this.s&&"idle"==a&&browser.windows.update(this.s,{focused:!0})};
n.sb=function(a,b,c){if(a.J){let e=a.tabId;a=a.g;let d=this.h[a];this.v&&this.W(4294967295);if(d&&d.D==e){let f=!1;b&&(d.H=b,f=!0);c&&(d.G=c,f=!0);tb(this,e,!1,f);this.fb(a,f,!1,500)}}else a.oa&&(b=this.g[a.h])&&b.postMessage([16,null,a.$,a.oa])};n.$b=function(a,b,c){(b=pa[b])&&fc(this,b,c,a)};n.cc=function(a,b,c){0==b&&fc(this,128,c,a)};n.ac=function(a,b,c,e){this.La=a.id;a.B=b;a.A=c;a.C=e};n.Vb=function(){fc(this,255,!1)};
n.Zb=function(a,b,c,e){var d=a.i;d&&(a=32,d=[d,null==c?(a|=16,-2):c],S(this,16,1,a,d,{[110]:b,[115]:e}))};n.wc=function(a,b,c){if(a=this.j[b])S(this,16,1,48,[a.id,0],{[115]:c}),a.Hb=!1,a.Ya&&this.L(a)};n.ic=function(a,b,c,e){S(this,19,2,0,[b,c,a.tabId,a.i],e)};n.Ub=function(a,b,c){if(a=this.j[b]){if(0>a.pa&&null!=c){a=new Uint8Array(c.length);for(let e=0;e<c.length;++e)a[e]=c.charCodeAt(e);c=a}S(this,16,1,48,[b,-1],{[115]:c});qc(this,b)}};
function qc(a,b){if(b=a.j[b])b.pa=null,b.eb=null,b.Ya&&a.L(b)}function tc(a,b){let c=a.i;if(b.Ha||a.o[b.tabId]||!c[-6])return 1;if(b.ga)return 6;if(b.Z&&c[-1])return 1;a=b.Ia;let e=b.gb=W(a.pathname);return c[9].test(a.hostname)||c[19].test(a.href)?1:2==(b.U&7)&&(b.Za||c[-10])?a.pathname.endsWith("/")||c[21].test(a.pathname)?1:c[1].test(e)||!c[20].test(e)?4:1:6}
function uc(a,b){let c=!b.X;if(b.ga&&c)return 3;let e=a.i;var d=e[18];let f=e[1];var g=b.Ia;let k=b.gb,h=b.fa||(g.search?null:k),m=b.Z,l=Ha.includes(b.type),q=!b.Za;var p=!l&&d.exec(g.href);if(p){var t=d.Hc,u=d.Ic;let w=d.Jc,x=d.Kc;for(d=1;d<p.length;++d)if(p[d]){t=t[--d];if(null===t)break;var v=void 0;p=0;t.includes("G")&&(v=!0,p|="GET"==b.method);t.includes("P")&&(v=!0,p|="POST"==b.method);if(v&&!p)break;v=t.includes("V")|t.includes("A")|t.includes("C");t.includes("H")&&(b.pb=!0);if((v?b.pb:m?!t.includes("S"):
t.includes("X"))||q&&t.includes("D"))return 1;let E,J,H;if(p=x[d]){p=p.exec(g.href);if(!p)break;g=u[d];if(u=g.F)H=!0,J=p[u];if(u=g.T)H=!0,E=p[u]}E||=W(J)||t.includes("T")&&(H=!0,k)||w[d];if(v)return E&&(b.gb=E),m||(b.Z=!0),b.X=!0,6;if(c&&(E?f.test(E):!H))return b.cb=16777216,4;break}}if(!c)return 6;if(h&&(l&&e[2].test(h)||m&&e[4].test(h)))return 1;if(y&&(b.Za||e[-10])){if(m&&e[3].test(h))return 6;if((!m||a.wa)&&h&&f.test(h))return b.cb=8,4}return 6}
function vc(a,b){if(b.Ob)return X(a,6,b),6;var c=b.statusCode;if(200!=c&&206!=c&&304!=c)return 1;var e=Z(b.qa,"Content-Type"),d=Z(b.qa,"Content-Disposition"),f=wc(e).toLowerCase();let g="attachment"==wc(d).toLowerCase();c=b.Z;var k=b.ha;if(b.Nb=k&&!g&&"text/html"==f){if(b.M){var h=Ib(a,b);h&&(h.M=!0);X(a,5,b)}return 1}if(c?b.Ha:b.X)return 1;if(a.wa&&k&&g)return 4;let m,l,q,p,t;var u;let v;let w,x=a.i,E=b.Ia;var J=E.hostname;let H=E.pathname,z=(d=xc(d,"filename")||xc(e,"name"))&&W(d);if(d){if(!z&&
!c)return 1;if(z&&(!c||5>=z.length)){var B=xc(e,"charset");w=!B||"utf-8"==B||"utf8"==B;B=!0}}B||(d=H.split("/").pop(),(z=b.gb||W(d))&&z.toLowerCase()==f.split("/").pop()&&(B=!0));if(!B){e=x[10].test(f);var M=ta[f];M&&(M=M.split("|"),z&&M.includes(z)?B=!0:c&&Ua(z)?B=!0:(c?e:z)||(B=!0,v=e,z=M[0]));!B&&z&&(g&&k?B=!0:e?B=v=!0:M||Ta(z)||(B=v=!0))}if(c){M=Nb(a,J);k=a.na[M];e=H+E.search;switch(M){case 0:break;case 1:if(k[111].test(e))m=B=!0,z=null;else if(k[112].test(e))l=!0;else if(k[115].test(e)&&"application/json"==
f)t=!0;else if(k[113].test(e)||k[114].test(e))q=!0;break;case 2:(J=k[111].exec(e))&&(Sa(f)||"text/html"==f)?(f=J[1]&&k[112].exec(b.port.u))&&J[1]!=f[1]||(q=!0):k[114].test(e)?t=!0:g&&"image"==b.type&&"MP4"==z&&(u=!0);break;case 3:"M4S"==z&&(B=!0);J==k[111]&&k[112].test(H)&&Sa(f)&&(q=!0);break;case 4:k[111].test(e)&&Sa(f)&&(t=!0);break;case 5:k[111].test(e)&&"text/html"==f&&(t=!0);break;case 6:k[111].test(e)&&(q=!0);break;default:k[111].test(H)&&(t=!0)}B&&("M3U8"==z||"F4M"==z||"MPD"==z?q=!0:"F4F"==
z&&(d.endsWith("Seg1-Frag1")||d.endsWith("Seg1-Frag2")||d.includes("Seg1-Frag2_"))&&(p=!0));"ASF"==z&&((f=Z(b.qa,"Content-Length"))&&102400>=parseInt(f)&&(u=!0),"DCLK-AdSvr"==Z(b.qa,"Server")&&(u=!0))}if(u)return 1;B&&(c&&x[3].test(z)?m=!0:c&&x[4].test(z)?b.X=!0:!b.X&&x[1].test(z)&&(h=!0));if(m){let Lb,Mb;if(b.pb)m=!1;else if(u=x[11])u.test(E.hostname)?m=!1:(Lb=a.g[b.tabId])&&(Mb=Lb.u)&&u.test((new URL(Mb)).hostname)&&(m=!1)}if(t)l=b.Hb=!0;else if(q||p)!b.port||"POST"==b.method&&!b.ba?l=!1:(b.pa=
p?-1:1,l=!0);if(!h&&!m&&!l)return 1;B&&(b.fa=z);w&&(b.fileName=d);b.M|=l;b.cb=m||l?256:16|(c?4096:0)|(v?8388608:0);return h?4:m?2:5}
function X(a,b,c,e,d){var f=c.url,g=c.U||T(f);let k=c.requestHeaders,h=1==(g&7);if(!e&&!k&&h)if(void 0===d){if(d=Z(k,"Cookie"),null==d)return U(f).then(x=>X(a,b,c,e,x||null))}else d=V(d);let m=e?e.id:c.id,l=c.port&&c.port.id,q=c.timeStamp,p=c.cb,t=c.qa,u=c.Ab,v=c.Ea,w=0;3==(v?v.length-v.replaceAll(".","").length:0)?p|=33554432:2<(v?v.length-v.replaceAll(":","").length:0)&&(p|=4194304);g&16&&(p|=2097152);"POST"==c.method&&(p|=512);e&&(w|=129);4>b&&y&&(w|=1);c.M&&c.pa&&(w|=1);c.M&&5!=b&&(w|=32);c.Z&&
(w|=16);c.Xa&&(w|=8192);c.ha&&(w|=c.J?2048:4096);g=[m,l,F(q),c.statusCode,g&7,b,c.tabId,c.frameId];f={[6]:Tb(f,h&&a.Y),[12]:c.statusLine,[17]:c.aa,[4]:c.fa,[100]:c.fileName,[127]:c.Oc,[129]:c.zc,[2]:c.Ea,[122]:a.A,[8]:p,[11]:yc(k),[13]:yc(t),[18]:yc(u)};c.ba&&(f[14]=pc(c.ba,k));c.bb&&(f[19]=pc(c.bb,u));k||(f[50]=zc(a,c),f[51]=d,f[54]=navigator.userAgent);y&&(f[122]=Fb(a,c.proxyInfo,Z(k,"Proxy-Authorization")),f[55]=Fb(a,c.Bb,Z(u,"Proxy-Authorization")));if(!c.Nb||!c.J)if(d=a.g[c.tabId])f[7]=d.u;return!!S(a,
13,1,w,g,f)}function Ac(a,b,c,e){if(y){if(X(a,b,c)){if(r&&!e){c.Wa=!0;return}return y?new Promise((d,f,g=a)=>{c.resolve=d;c.reject=f;Gb(g,c)}):a.L(c,!0)}c.X=!0}else c.Mb=!0}
n.L=function(a,b,c){let e=this.j,d;if(A(a)||(a=e[a])){var f=a.id,g=0<a.statusCode;if(b){if(a.ha||a.Xa)c=g||!a.requestHeaders,(g=Ib(this,a))&&g.j&&a.J?browser.tabs.remove(a.tabId):r&&c&&!a.Xa&&(d={redirectUrl:"javascript:void(0)"});d||={cancel:!0};a.Wa=!0}else c&&(d={[g?"responseHeaders":"requestHeaders"]:c});(c=a.resolve)&&void 0!==b&&(a.resolve=a.reject=null,c(d||{}));if(b=a.reject)a.resolve=a.reject=null,b();if(a.Pa||a.pa||a.Hb)return a.Ya=!0,d;delete e[f];a.eb&&delete e[a.eb];a.ra&&delete e[a.ra];
return d}};
n.xb=function(a){var b=a.type,c=a.tabId,e=a.frameId;if(!(0>c&&(y?a.originUrl==Pa:a.initiator==Oa))){var d=a.url,f=a.method,g=T(d);if(g&&("GET"==f||"POST"==f)&&d!=this.jb){e&&"outermost_frame"==a.frameType&&(e=a.frameId=0);var k=a.id=a.requestId,h=this.j[k],m=this.Sa,l="POST"==f,q="image"==b,p=r&&"other"==b,t=!p&&0>c&&(y||0>e),u=0<c&&b.endsWith("_frame"),v=t?null:this.g[P(c,e)];if(v||u||t||p||h){y&&l&&h&&ab(h.statusCode)&&(f=a.method="GET",l=!1);u&&Hb(this,a,null,!1);if(!m&&l&&a.requestBody){l=a.requestBody;
var w=l.raw;if(w)for(let x=0;x<w.length&&(w[x].bytes||(w=null));x++);if(!(w||l.formData||r&&l.error))return}if((l=this.La)&&(w=v?v.id==l&&v:this.m[l])&&d==w.A){p=w.B;if(l=w.C)a.fileName=l,a.fa=W(l);v||=w;this.La=null}l=new URL(d);l.hash="";a.Ia=l;a.U=g;a.ga=this.ta;a.Ha=m;a.J=u&&"main_frame"==b;a.ha=u;a.Xa=p;a.Jb=t;a.Z=t||Ia.includes(b);a.X=q;a.M=this.nb.test(d);a.ba=a.requestBody;a.port=v;a.Za=g&8||(y?a.proxyInfo&&"https"==a.proxyInfo.type:this.Da[g]);0>c&&(a.tabId=null);0>e&&(a.frameId=null);if(h)a.id=
h.id,a.port=v=h.port,a.ga=h.ga,a.Ha=h.Ha,a.aa=h.aa||h.url,a.Ab=h.Ab||h.requestHeaders,a.bb=h.bb||h.ba,y&&(a.Bb=h.Bb||h.proxyInfo);else if(y&&t)for(let x of C(this.j))if(x.Mc&&!x.ra&&d==x.url&&b==x.type&&f==x.method){a=x;a.ra=k;break}if(a.Z&&!q){b=this.xa;c=b.yc;e=c.indexOf(d);if(0<=e)c.splice(e,1);else for(;30<=c.length;)delete b[c.shift()];b[d]=v;c.push(d)}switch(a.action=tc(this,a)){case 1:a.X=!0;case 6:Gb(this,a);break;case 4:return Ac(this,1,a)}}}}};
n.pc=function(a){var b=this.j[a.requestId],c;if(b){var e=b.requestHeaders=a.requestHeaders;b.timeStamp=a.timeStamp;if(!b.Wa){if(b.Jb&&!b.port&&(a=Z(e,"Referer")))for(var d of C(this.m))if(d.u==a){b.port=d;break}if(b.port&&"xmlhttprequest"==b.type){var f;d=0;for(var g of e)if("accept"==g.name.toLowerCase()&&(f=Xa(g.value)))break;else d++;if(f){g=f[3];a=f[4];if(c=y)f[1]||f[5]?e[d].value=f[1]+(f[5]&&f[2]||"")+f[5]:e.splice(d--,1);if("int"==g)return this.L(b,!1,c&&e);if("pxr"==g||"pfm"==g)b.eb=a,this.j[a]=
b}}y&&b.proxyInfo&&Fb(this,b.proxyInfo,Z(e,"Proxy-Authorization"),!0);if("POST"==b.method&&(!b.ba||b.ba.error&&0<Z(e,"Content-Length")))return this.L(b);switch(b.action=uc(this,b)){case 1:b.X=!0;break;case 4:return Ac(this,1,b);case 3:return Ac(this,3,b)}if(c)return{requestHeaders:e}}}else if(y&&0>a.tabId&&"xmlhttprequest"==a.type&&(y?a.originUrl==Pa:a.initiator==Oa)){b=a.requestHeaders;e={};for(f=0;f<b.length;f++)g=b[f],d=g.name.toLowerCase(),d.startsWith("x-idm-")?e[d.substr(6)]=c=!0:"origin"==
d&&g.value==Oa&&(e[d]=c=!0);if(c){for(c=0;c<b.length;c++)f=b[c],g=f.name.toLowerCase(),e[g]?b.splice(c--,1):g.startsWith("x-idm-")&&(f.name=f.name.substr(6));return{requestHeaders:b}}}};n.oc=function(a){if(!a.statusCode&&a.redirectUrl==a.url){a=a.requestId;let b=this.j[a],c=b&&Ib(this,b);c&&!b.statusCode&&c.i==a&&(b.Mc=!0)}};
n.sc=function(a){let b=this.j[a.requestId];if(b){var c=b.statusLine=a.statusLine,e=b.statusCode=a.statusCode||parseInt(c.split(" ",2).pop()),d=a.responseHeaders;if(b.Wa||204==e&&c.includes(" IDM "))return this.L(b,!0);b.Ea=a.ip;b.Fb=a.timeStamp;b.zc=F(a.timeStamp-b.timeStamp);b.qa=d;b.Ob=$a(e);if("image"==b.type&&(c=Z(d,"Content-Type"))&&c.toLowerCase().startsWith("image"))return this.L(b);"quic"==Z(d,"Client-Protocol")?b.U|=16:(c=Z(d,"Alternate-Protocol"))&&c.endsWith(":quic,p=0")&&"chunked"!=Z(d,
"Transfer-Encoding")&&(b.U|=16);switch(b.action=vc(this,b)){case 1:return y&&this.L(b);case 4:return Ac(this,2,b,a);case 3:return Ac(this,3,b,a)}}};n.tc=function(a){let b=this.j[a.requestId];if(a.type.endsWith("_frame")&&(200==a.statusCode||304==a.statusCode)){let c=Ib(this,a);c&&(c.u=a.url,c.aa=c.o)}b&&(b.Ea||(b.Ea=a.ip),2==b.action?X(this,4,b):5==b.action&&X(this,5,b),y&&this.L(b))};n.qc=function(a){(a=this.j[a.requestId])&&(y||!a.Mb||a.Pa?this.L(a):K.setTimeout(this.L,250,a))};n.rc=function(a){this.L(a.requestId)};
async function mb(a){var b={url:L.homepage_url};wa&&(b.firstPartyDomain=null);var c=browser.storage.local.get(null);b=browser.cookies.getAll(b);let e=browser.extension.isAllowedIncognitoAccess();[c,b,e]=await Promise.all([c,b,e]);a.Eb=c.version;a.Aa=c.silent;a.la=c.lastupt;a.mb=e;y&&(a.N=!!c.consent);c=c.client;let d;if(b)for(let f of b)switch(f.name){case "idmwebext_cid":d=parseInt(f.value);break;case "idmmzcc3_uri":a.lb=f.value==Oa}jc(a,null,c,d);a.Na()}
function jc(a,b,c,e){(b||=c||e)&&b!=a.ua&&(a.ua=b,c||browser.storage.local.set({client:b}),e||browser.cookies.set({url:L.homepage_url,name:"idmwebext_cid",value:String(b),expirationDate:2147483647}))}
function Pb(a){function b(m){m&&(this.O=m.id)}a.O&&(browser.tabs.remove(a.O),a.O=null);if(a.Gb||!a.N){var c=!a.G,e=!a.mb,d=!a.N,f=a.Y,g=a.sa,k=a.Eb,h=a.Ua;if(c){if(a.za&&a.Aa)return}else a.Gb=!1,h!=k&&(h&&browser.storage.local.set({version:h}),y&&browser.cookies.set({url:L.homepage_url,name:"idmmzcc3_uri",value:Oa,expirationDate:2147483647})),a.Aa&&(a.Aa=!1,browser.storage.local.set({silent:!1}));if(null!=k&&(d=!1,a.N=!0,h!=k?g&&k&&!f&&!d:!d))return;h=Na+"current="+escape(h);k&&(h+="&previous="+escape(k));
g&&(h+="&manager="+(g?[g>>24&255,g>>16&255,g>>8&255,g&255].join("."):""));c&&(h+="&error=1");e&&(h+="&incognito=1");f&&(h+="&update=1");d&&(h+="&consent=1");y&&(h+="&mzffox=1");ba&&(h+="&opera=1");aa&&(h+="&msedge=1");d&&!c?(browser.idle&&a.I(5,browser.idle.onStateChanged,a.Yb)&&browser.idle.setDetectionInterval(15),browser.windows.create({type:"popup",width:Math.min(Math.round(.85*screen.availWidth),1100),height:Math.min(Math.round(.85*screen.availHeight),900),url:h}).then(m=>{m&&m.id?(a.s=m.id,
a.O=m.tabs[0].id,R(a,!1,null,!0)):ob(a)})):browser.tabs.create({url:h},b.bind(a))}}function kc(a,b,c){null==b&&(b=Za(c[13]))&&(b=b[1]<<24|b[2]<<16|b[3]<<8);a.sa=b>>>0}function lc(a){a.Y=103418624>a.sa;103424E3>a.sa?a.K=a.la?a.la+6E4*F(240*G()+480):Date.now():(a.K=a.la=null,browser.storage.local.remove("lastupt"))}
function Wb(a,b){var c=Date.now();if(c>a.K||b&&!a.Y)browser.storage.local.set({lastupt:a.la=c}),0<a.K&&(a.K=c+6E4*F(240*G()+480)),c="idmdwnlmfv4://idmreg://"+G().toString(36).substr(2),b?a.ja(c):K.setTimeout(a.ja,F(5E3*G()+5E3),c)}function zc(a,b){a=a.C;b=P(b.tabId,b.frameId);var c;do b=(c=a[b])&&c.h,c=c&&c.u,"about:blank"==c&&(c=null);while(!c&&b);return c}
function Vb(a,b){b=browser.i18n.getMessage(b);browser.scripting.executeScript({target:{tabId:a},func:function(c){window.alert(c)},args:[b]},Ob)}n.I=function(a,b,c){if(null==b)return!1;let e=ha(arguments);y&&(e[2]=function(){return c.apply(null,arguments)});this.hb.push(e);b.addListener.apply(b,e.slice(2));return!0};
n.Ma=function(){let a=arguments.length?ha(arguments):null,b=this.hb;for(let c=0;c<b.length;c++){if(a&&!a.includes(b[c][0]))continue;let e=b.splice(c--,1).pop(),d=e.splice(0,2).pop();d.removeListener.apply(d,e)}};function zb(a){return browser.i18n.getMessage(a)||a}function Tb(a,b){let c=a.lastIndexOf("#");c>a.indexOf("?")&&"!"!=a[c+1]&&(a=a.substr(0,c));!b||a.startsWith("idmdwnlmfv")||Va(a)||(a=`${"idmdwnlmfv"}4://${a}`);return a}
function T(a,b){a=a.split(":",1).shift().toLowerCase();a=qa[a]||0;return b?a&7:a}function W(a){return(a=Ya(a))?a[1].toUpperCase():""}function U(a,b){a={url:a};b&&(a.session=!1);wa&&(a.firstPartyDomain=null);return browser.cookies.getAll(a).catch(()=>null)}function V(a){if(!A(a))return a;let b=[];for(let c of a)b.length&&b.push("; "),b.push(c.name,"=",c.value);return b.join("")}
function yc(a){if(!a||!a.length)return null;let b=[];for(let c of a)b.push(c.name,": "),null!=c.value?b.push(c.value):c.binaryValue&&b.push(new Uint8Array(c.binaryValue)),b.push("\r\n");return b}function Z(a,b){if(!a)return null;b=b.toLowerCase();for(let c of a)if(c.name.toLowerCase()==b){if(null!=c.value)return c.value;if(c.binaryValue)return ka(c.binaryValue)}return null}
function xc(a,b){if(!a)return null;let c,e;a=a.split(";");for(b=b.toLowerCase();a.length;){var d=a.shift();let g=d.indexOf("=");if(0<g){var f=d.slice(0,g).trim().toLowerCase();let k=f.endsWith("*");if(k)f=f.slice(0,-1).trimRight();else if(e)continue;if(f==b){f=d.substr(g+1).trim();d=f.length-1;if('"'==f[0]?'"'==f[d]:"'"==f[0]&&"'"==f[d])f=f.slice(1,d);if(k&&f.includes("'")){if(f=f.split("'",3),k=f.shift().toLowerCase(),f=f.pop(),((d="utf-8"==k||"utf8"==k)||!e)&&(c=Bc(f))&&(e=k,d))break}else c=Bc(f)}}else 0>
g&&null==c&&d.trim().toLowerCase()==b&&(c="")}return c}function wc(a){const b=/[;,]/;return(a&&=a.split(b,1).shift().trim())&&!a.includes("=")&&Bc(a)||""}function Bc(a){try{return a&&decodeURIComponent(a)}catch(b){return unescape(a)}}
function pc(a,b,c){let e;var d;let f=[];if(e=a.raw)for(d of e){var g=d.bytes;if(g)f.push(c?ka(new Uint8Array(g)):g);else return null}else if(d=a.formData)if(b=fa(b)?Z(b,"Content-Type"):b,(a=wc(b).toLowerCase())&&"application/x-www-form-urlencoded"!=a)if("multipart/form-data"==a){var k=xc(b,"boundary");k||="----WebKitFormBoundary"+G().toString(36).substr(2);for(g in d)for(let h of d[g])c&&h instanceof ArrayBuffer&&(h=ka(new Uint8Array(h))),f.push("--",k,'\r\nContent-Disposition: form-data; name="',
g,'"\r\n\r\n',h??"","\r\n");f.push("--",k,"--\r\n")}else return null;else for(k in d){g=encodeURIComponent(k).replaceAll("%20","+");for(let h of d[k])h=h instanceof ArrayBuffer?escape(ka(new Uint8Array(h))):null==h?"":encodeURIComponent(h),f.length&&f.push("&"),f.push(g,"=",h&&h.replaceAll("%20","+"))}else return null;c&&(f=f.join(""));return f.length?f:null}function fb(a){let b=a.length,c=b,e=0;for(;e<c;){let d=a.charCodeAt(e++);128<=d&&(2048<=d?(b+=2,d-55296&64512||e++):b++)}return b}
function Cc(){let a="llbjbkhnmlidjebalopleeepgdfgcpec"==Aa&&"ngpampappnmepgilojfohadhhmbhlaek";browser.management.get(a||"llbjbkhnmlidjebalopleeepgdfgcpec",function(b){browser.runtime.lastError;b&&b.enabled&&browser.management.setEnabled(a||Aa,!1)})}
function Cb(a,b){a=a.replace(/^\|+|\|+(?=\||$)/g,"").replace(/\./g,"\\.");a=1==b?a.replace(/\?/g,"[^/\\\\]").replace(/(^|[^*])\*(?!\*)/g,"$1[^/\\\\]*").replace(/\*\*/g,".*?"):3==b?a.replace(/(?<![*?])\*(?!\*)/g,"[^/]*").replace(/\?\*/g,"\\?.*").replace(/\*\*/g,".*?"):a.replace(/\?/g,".").replace(/\*/g,".*?");2==b&&(a=a.replace(/(^|\|)([^|]+?)~/g,"$1(?:$2\\.)?").replace(/(^|\|)~/g,"$1(?:.*?\\.)?"));return`^(?:${a})$`}
function Y(a,b,c,e){if(b=b[c]||void 0){b=Cb(b,e);try{b=RegExp(b,1==e?"":"i")}catch(d){b=null}}a[c]=b||Fa}
function mc(a,b,c,e,d){b=b[c];let f=[],g=[],k=[],h=[];if(b)try{b=b.replace(/^\|+|\|+(?=\||$)|\*+(?=\*)/g,"").replace(/[.?+(){}[\]]/g,"\\$&").replace(/\*(?=[^:/|&]*:\/\/)/g,"\\w%%").replace(/(:\/\/[^:/]*?)~/g,"$1(?:\\b[^./]+\\.)?").replace(/\\\?(?=\||$)/g,"(?:$&.%%)?");if(e){for(var m=b.replace(/(^|\|)(?:([A-Z]+)?(?:#(\w+))?!)?[^|]+/g,"$1$2|$3").split("|");m.length;){var l=m.shift();f.push(Wa(l)?l:null);g.push(m.shift())}b=b.replace(/(^|\|)[\w#]+!/g,"$1")}if(d){let q=b.replace(/(^|\|)(?:(?=[^|]+?<[A-Z]:.*?>)|[^|]+)/g,
"$1").split("|");m=/<([A-Z]):(.*?)>/g;l={F:"[^/\\?#&;]%%",T:"[^/\\?#&;.]%%"};for(let p,t=0;q.length;++t)if(p=q.shift()){let u={},v=["^"],w="";for(let x,E=1;x=m.exec(p);++E)u[x[1]]=E++,w=RegExp.rightContext,v.push(RegExp.leftContext,"(",x[2].replace(/\*/g,l[x[1]]||".%%?"),")");v.push(w,"$");k[t]=u;h[t]=RegExp(v.join("").replace(/\*/g,".*?").replace(/%%/g,"*"))}b=b.replace(m,"(?:$2)")}b=b.replace(/\*/g,".*?").replace(/%%/g,"*");b=e||d?RegExp("^(?:("+b.replace(/\|/g,")|(")+"))$"):RegExp("^(?:"+b+")$")}catch(q){b=
null}a[c]=b||=RegExp("(?!)");e&&(b.Hc=f,b.Jc=g);d&&(b.Ic=k,b.Kc=h)}function ic(a){return browser.runtime.lastError?null:browser.permissions.request({permissions:[a]})}function Ob(a){browser.runtime.lastError;a;!0}
const qb=[null,[!0,-8,"menu_download_link","link,image,video",Q.prototype.Qa],[!0,-8,"menu_download_link","page,frame,editable",Q.prototype.Qa,La],[!0,-8,"menu_download_selected","selection",Q.prototype.ib],[!0,-9,"menu_download_all","page,frame,editable",Q.prototype.ib],[r,-8,"menu_download_item","link",Q.prototype.Qa,["chrome://downloads/*"]]],vb=zb("tooltip_title"),xb=zb("tooltip_disabled"),yb=zb("tooltip_error"),wb="\n"+zb("tooltip_text");
(async function(){var a=browser.runtime.getPlatformInfo();let b,c;navigator.userAgentData?b=navigator.userAgentData.getHighEntropyValues(["fullVersionList","uaFullVersion"]):b=browser.runtime.getBrowserInfo?.();c=browser.privacy?.websites?.firstPartyIsolate?.get({});var e=r&&browser.management.get("clhiejnehegdfknplplojohghjaklbae").catch(()=>null);[a,b,c,e]=await Promise.all([a,b,c,e]);if(a&&"win"!=a.os)return ub(!1);aa&&Cc();a=navigator.userAgent;var d=a.match(/\s(?!(?:Chrome|Firefox|Gecko|Safari)\/)([A-Z]\w+)(?:\/(\d+(?:\.\d+){0,3}))?\b(?!.*\)\s+\S)/),
f=a.match(/\s(Chrome|Firefox)\/(\d+(?:\.\d+){0,3})\b/);a=f?f[1]:"UNKNOWN";let g=d?d[1]:a;f=f&&f[2]||"0.0";d=d&&d[2]||f;y&&(a="Mozilla");r&&navigator.brave&&(g="Brave");r&&e&&(g="Epic",xa=!0);if(A(b)){if(e=b.uaFullVersion)d=e;if(e=b.fullVersionList)for(let k of e){if(e=k.version)switch(k.brand){case "Chromium":a="Chrome";parseInt(e)==parseInt(f)?f=e:(g="UNKNOWN",d=e);break;case g:d=e}}else if(e=b.version)if(53<=parseInt(e)&&(f=e),e=b.name)g=e}e=f.split(/\D+/);ua=a+"/"+f;va=g+"/"+d;browser.webRequest.ResourceType.OBJECT_SUBREQUEST&&
(N.push("object_subrequest"),Ia.push("object_subrequest"));A(c)&&(wa=c.value);new Q})();
