var h;
if(!window.__idm_init__&&navigator.platform.startsWith("Win")&&"html"==document.documentElement.localName){window.__idm_init__=!0;"undefined"==typeof browser&&(browser=chrome);navigator.userAgent.includes("Edg/");navigator.userAgent.includes("Firefox/");navigator.userAgent.includes("OPR/");navigator.userAgent.includes("YaBrowser/");const N=Object.values,O=RegExp.prototype.test,P=Array.from,Q=Array.prototype.includes;Array.prototype.concat.bind([]);const aa=Math.random,R=Function.call.bind(Array.prototype.slice),S=
Function.apply.bind(Array.prototype.push),G=Function.call.bind(Array.prototype.forEach),ba=Function.apply.bind(String.fromCharCode,null),H="dotAll"in RegExp.prototype?"s":"",ca=Function.call.bind(String.prototype.charCodeAt),da=String.fromCharCode;Function.bind.bind(function(a){return this[a]});Function.bind.bind(function(a){return a&&a[this]});TextDecoder.prototype.decode.bind(new TextDecoder("ascii"));TextEncoder.prototype.encode.bind(new TextEncoder("utf-8"));O.bind(/^(?:Host|Origin|Referer|Cookie|User-Agent|Connection|DNT|Accept-Encoding|Sec-.+)$/i);
Array.prototype.at||(Array.prototype.at=function(a){0>a&&(a+=this.length);return this[a]});AbortSignal.timeout||(AbortSignal.timeout=function(a){let b=new AbortController;globalThis.setTimeout(b.abort.bind(b),a);return b.signal});function ea(a,b){return fetch(a,b).catch(()=>null)}function fa(a,b){b&&(a[b]=!0);return a}function B(a){return a.replace(/[a-z]/gi,function(b){return da((b=ca(b))+(13<(b&31)?-13:13))})}const ha={16:!0,17:!0,18:!0,45:!0,46:!0},K=Q.bind(["video","audio","object","embed"]),
z=RegExp("(?!)"),ia=RegExp(" *\\$([<>{}|&*+=@!#%:?^~-])(\\d*) *"),ja=O.bind(/^rgba?\(\d+,\s*\d+,\s*\d+,\s*0\)/),I=window.self===window.top;var D=window.origin||document.origin||location.origin,J=location,L=location.hostname.toLowerCase()+location.pathname+location.search,T=location.hostname.toLowerCase().split(".").at(-2),U=`idmrs://${T}/`,ka=T?RegExp(`^(?:\\(\\d+\\)\\s+)?(.+?)\\s+[-|@]+\\s*${T}$`,"i"):z;function V(){browser.runtime.getFrameId?this.ga=browser.runtime.getFrameId(window):I&&(this.ga=
0);this.Aa=[];this.R=[];this.T=[];this.l={};this.Za();window.__idm_connect__=this.Za.bind(this,!0);this.h(1,window,"resize",this.jc);this.h(1,window,"scroll",this.kc);this.h(1,window,"blur",this.ac);this.h(1,window,"keydown",this.hb,!0);this.h(1,window,"keyup",this.hb,!0);this.h(1,window,"mousedown",this.cc,!0);this.h(1,window,"mouseup",this.ec,!0);this.h(1,window,"mousemove",this.dc,!0);this.h(1,window,"click",this.bc,!0);this.h(1,document,"beforeload",this.Zb,!0);this.h(1,document,"DOMContentLoaded",
this.gb);"interactive"!=document.readyState&&"complete"!=document.readyState||this.gb()}h=V.prototype;h.u=0;h.A=0;h.ha=-1;h.ia=-1;h.kb=1;h.U=0;h.m="";h.Ga="";h.H="";h.ja=B("KZYUggcErdhrfg|bcra|fraq|frgErdhrfgUrnqre|hcybnq|ybnqraq|erfcbafrGrkg|srgpu|urnqref|obql|grkg|wfba|trgErnqre|cvcrGuebhtu|Urnqref|npprcg|*/*|nccyvpngvba/iaq.g1p");h.Na=z;h.Ua=RegExp(B('\\olgpst\\.frg\\(\\{(?=.*?"RKCREVZRAG_SYNTF":)(?=.*?"FGF":(\\q{5,})\\o|)(?=.*?"QNGNFLAP_VQ":"(.+?)"|)(?=.*?"YBTTRQ_VA":(\\j+)\\o|)(?=.*?"RBZ_IVFVGBE_QNGN":"(.+?)"|)(?=.*?"IVFVGBE_QNGN":"(.+?)"|)(?=.*?"CYNLRE_WF_HEY":"(.+?)"|)(?=.*?"FRFFVBA_VAQRK":"(\\q)"|)'),
H);h.I=z;h.Wa=z;h.Oa=z;h.G={};h.Pa="(?!)";h.Qa="(?!)";h.Ra=B('\\oshapgvba\\((\\j+)\\)\\{ine\\f+(\\j+)=[^?;,]*?(?:\\.fcyvg\\.\\j+\\(\\1,|\\1\\.fcyvg\\()(?:.+?\\ovs\\f*\\(glcrbs\\f+([\\j$]+)===?(([\\j$]+)[^()]+|"haqrsvarq")\\)\\s*return\\b)?.+?\\{return\\s+(?:([\\w$]+)\\[\\d+\\]|[^();,]+?)\\+\\s*\\1\\}\\s*return\\b[^{};]+?(?:\\.join\\.\\w+\\(\\2,|\\2\\.join\\b)[^{};]+?\\}');h.Sa=B("(?<=\\oine\\f+)${3.3}=.+?(?=[;,}])");h.Ta=B("(?<=\\oine\\f+)${3.5}=(([\"']).*?\\2\\.fcyvg\\(([\"']).\\3\\)|\\[(?:(?:\".*?\"|'.*?')(?:,\\s*|(?=\\])))+\\])(?=[;,])");
h.Va=B('$> *[ebyr="znva"]:abg(uvqqra) ivqrb, :fpbcr >qvi#cynlre ivqrb, lgzhfvp-cynlre qvi#fbat-vzntr vzt');h.Ma=B("$<< $> :fpbcr >ivqrb +qvi >pnainf");h.Xa=B("$= lg.pbasvt_.RBZ_IVFVGBE_QNGN $= lgpst.qngn_.RBZ_IVFVGBE_QNGN $= lg.pbasvt_.IVFVGBE_QNGN $= lgpst.qngn_.IVFVGBE_QNGN");h.oa=z;h.la=":root:empty";h.na=0;h.ma=z;h.ta=z;h.ua='$& div.xxzkxad $& :scope >div[class] $& section main[role="main"] $& div.xw7yly9 >div >div[style]:only-child $& div >article <';h.wa='$& div.xxzkxad $& :scope >div[class] $& section main[role="main"] $& div:first-child >div[role="button"][aria-hidden], article[role="presentation"] $& div:first-child >div[style]:first-child:empty < $& div[role="presentation"] >div >ul';
h.sa='$+ article:scope, div.x1xfsgkm:scope $* main[role="main"] article, main[role="main"] >div >div.x1xfsgkm';h.xa="$= poster $< <<<<<< $> div:scope >img:first-child, div[data-instancekey] div >img:first-child $= src";h.va=RegExp("/(?:p|reel|reels|stories/[\\w.-]+)/([\\w-]{11}|\\d{19})(?:[/?#]|$)");h.Ha=z;h.Ia=RegExp("^(?:[^/]+|player\\.vimeo\\.com/video)/(\\d{2,})");h.La="$| video:scope $| video";h.Ja="$> :scope >div.player";h.Ka="$& div.vp-video $& div.vp-telecine";h.Za=function(a){this.ib(-1);
this.g=a=browser.runtime.connect({name:(I?"top":"sub")+(a?":retry":"")+("file:"==location.protocol?":file":"")});this.h(-1,a,"onMessage",this.hc);this.h(-1,a,"onDisconnect",this.fc)};h.fc=function(){browser.runtime.lastError;this.ib();this.g=this.S=null;window.__idm_init__=!1;window.__idm_connect__=null};h.hc=function(a){switch(a.shift()){case 11:this.Fb.apply(this,a);break;case 17:this.Gb.apply(this,a);break;case 12:this.Ib.apply(this,a);break;case 13:this.zb=a.shift();break;case 14:this.Lb.apply(this,
a);break;case 15:this.Mb.apply(this,a);break;case 16:this.Ob.apply(this,a);break;case 18:this.Kb.apply(this,a);break;case 19:this.Nb.apply(this,a)}};h.mc=function(a,b){var c=105<=this.O;let d=108<=this.O;switch(this.j=a){case 1:this.s=this.Hb=!0;if(a=b.shift())this.m=a;if(a=b.shift())this.Na=RegExp(a,H);if(a=b.shift())this.I=RegExp(a);if(a=b.shift())this.Wa=RegExp(a);if(a=b.shift())this.G=a.split(/[|:]/).reduce(fa,{});if(a=b.shift())this.Oa=RegExp(a);if(a=b.shift())this.Pa=a;if(a=b.shift())this.Qa=
a;(a=b.shift())&&c&&(this.Ra=a);(a=b.shift())&&c&&(this.Sa=a);(a=b.shift())&&c&&(this.Ta=a);(a=b.shift())&&d&&(this.Ua=RegExp(a,H));(a=b.shift())&&d&&(this.Va=a);if(a=b.shift())this.Ma=a;if(a=b.shift())this.Fa=a;if(a=b.shift())this.Pb=a;if(a=b.shift())this.Xa=a;if(a=b.shift())this.Qb=a;break;case 2:this.ab();this.s=!0;if(a=b.shift())this.m=a;if(a=b.shift())this.H=a;if(a=b.shift())this.oa=RegExp(a);if(a=b.shift())this.nb=a;if(a=b.shift())this.qb=a;b.shift();if(a=b.shift())this.qa=a.startsWith("$")?
a:`$< ${a.slice(1)} <`;if(a=b.shift())this.rb=a;if(a=b.shift())this.mb=a.startsWith("$")?a:`$* ${a}`;if(a=b.shift())this.ra=a.startsWith("$")?a:`$< ${a.slice(1)} <`;if(a=b.shift())this.jb=a;if(a=b.shift())this.la=a;if(a=b.shift())this.sb=a.startsWith("$")?a:`$* ${a}`;if(c=b.shift())this.na=c;if(a=b.shift())this.ob=a;if(a=b.shift())this.ma=RegExp(a);break;case 4:this.ab();this.s=!0;if(a=b.shift())this.m=a;if(a=b.shift())this.Ga=a;if(a=b.shift())this.H=a;if(a=b.shift())this.ta=RegExp(a);if(a=b.shift())this.vb=
a;if(a=b.shift())this.ua=a;if(a=b.shift())this.wa=a;if(a=b.shift())this.xb=a;if(a=b.shift())this.sa=a;if(a=b.shift())this.tb=a;if(a=b.shift())this.ya=a;if(a=b.shift())this.xa=a;b.shift();if(a=b.shift())this.ub=a;if(a=b.shift())this.va=RegExp(a);break;case 3:if(a=b.shift())this.Ha=RegExp(a);if(a=b.shift())this.Ia=RegExp(a);if(a=b.shift())this.La=a;if(a=b.shift())this.Ja=a;if(a=b.shift())this.Ka=a;break;case 5:this.s=!0;if(a=b.shift())this.m=a;if(a=b.shift())this.H=a;if(a=b.shift())this.yb=a;break;
default:this.s=!0;if(a=b.shift())this.m=a;if(a=b.shift())this.Ea=a}this.m.includes("^/")&&((b=this.Ga)?b="https?://"+b.slice(+b.startsWith("^"),-b.endsWith("$")||void 0):b=D.replaceAll(".","\\."),this.m=this.m.replaceAll("^/",`^(?:${b})?/`))};h.aa=function(a){if(this.j&&this.N(arguments))switch(this.j){case 1:this.Yb(a);break;case 2:this.Ub(a);break;case 4:this.Vb(a);break;case 3:this.Xb(a);break;case 5:this.Wb(a)}};h.X=function(a){let b=this.g;for(let c of document.getElementsByTagName("script"))!c.src&&
a.test(c.text)&&b.postMessage([34,null,-1,c.text]);b.postMessage([34,this.B()])};h.da=function(a,b,c,d){if(this.lb&&c){let e=a instanceof Element?this.M(a):0,f=this.T,g=f.indexOf(null);0>g&&(g=f.length);f[g]=[a,b,d];this.ea(1229212980,g,e,c)}else d(a,b)};h.ic=function(a,b){var c=this.T.splice(a,1,null).shift();if(c){a=c[0];let d=c[1];c=c[2];a instanceof Element&&!document.contains(a)&&(b=void 0);c(a,d,b)}};h.lc=function(a){let b=a.data;if(Array.isArray(b)&&a.origin==D)switch(b[0]){case 1229212977:this.lb=
!0;this.ea(1229212978,this.S,this.o,this.ja,this.s,this.Hb,this.m,this.H);break;case 1229212979:this.g.postMessage([36,b[1],b[2]]);break;case 1229212981:this.ic(b[1],b[2])}};h.ea=function(a,b){window.postMessage(R(arguments),"/")};h.Y=function(){let a=window.devicePixelRatio,b=document.width,c=document.body.scrollWidth;b&&c&&(a=b==c?0:b/c);return a};h.ab=function(){this.o||(this.o=btoa(aa().toString().substr(2,9)))};h.M=function(a){let b=a.v;b||(b=a.v=this.S<<13|this.kb++,this.l[b]=a,this.o&&a.setAttribute(this.o,
b));return b};h.K=function(a){a.C&&(window.clearTimeout(a.C),a.C=null);a.l&&(a.l.disconnect(),a.l=null);this.P&&this.P.unobserve(a);this.D&&this.D.unobserve(a);delete this.l[a.v];a.v=a.j=a.g=null};h.Ya=function(a,b,c){let d=this.M(a);if(b||c){for(let e of N(this.l))if(b?b==e.j:c==e.g)return;a.g=c||=U+a.localName+"/"+b;a.j=b;this.i&&a.setAttribute("__idm_uri__",c)}a.l||(b=a.l=new MutationObserver(this.ba.bind(this)),this.i&&a.setAttribute("__idm_obs__",1),b.observe(a,{attributes:!0,attributeFilter:["style"]}),
b.observe(a.parentElement,{childList:!0}),this.P&&this.P.observe(a));1==this.j&&t(a,this.Fa)&&(a.s=!0,a.D=10);return d};h.F=function(a,b,c,d){if(b=this.Ya(a,b,c))d&&this.D&&this.D.observe(a),d=this.L(a),this.g.postMessage([41,b,a.localName,a.src||a.data,a.g,a.j,d])};h.Eb=function(a,b,c,d,e,f){let g,n,k,m;let l,p,r=window.getComputedStyle.bind(window);try{let v=0;k=document.activeElement;k&&K(k.localName)||(k=document.elementFromPoint(this.ha,this.ia))&&!K(k.localName)&&(k=null);for(let q of document.querySelectorAll("video,audio,object,embed")){let C=
q.localName,x;var w="object"==C||"embed"==C;if(w){let F=q.type.toLowerCase();if(F.startsWith("text/")||F.startsWith("image/"))continue;if("embed"==C&&"application/x-shockwave-flash"!=F)continue}if(q.g&&!q.s&&(e||f))if(e?e==q.j:f==q.g)g=q;else continue;else if(x=q.src||q.data)x!=a&&x!=b||(g=q);else if(!w)for(let F of q.getElementsByTagName("source"))if((x=F.src)&&(x==a||x==b)&&(g=q))break;if(g)if("cover"==r(q).objectFit)n=q,g=null;else break;if(n||k||m)continue;if(x){if((x==c||x==d)&&(m=q))continue;
if("video"==C&&x.startsWith("data:audio/"))continue}let A=q.clientWidth,y=q.clientHeight;if(!A||!y)continue;let W=q.getBoundingClientRect();if(0>=W.right+window.scrollX||0>=W.bottom+window.scrollY)continue;let X=r(q);if(q.Z||"hidden"==X.visibility||"none"==X.display)"video"==C&&(p||=q);else{w=A*y;if(v<w&&1.35*A>y&&A<3*y){v=w;var u=q}l||=q}}}catch(v){}(a=g||n||k||m)?"video"!=a.localName&&"hidden"==r(a).visibility&&(a=null):a=u||l||p;a&&("embed"!=a.localName||a.clientWidth||a.clientHeight||(u=a.parentElement,
"object"==u.localName&&(a=u)),this.Ya(a,e,f));return a};h.Db=function(a,b,c){let d=null,e,f=browser.runtime.getFrameId;for(let g of document.getElementsByTagName("iframe")){let n=g.o;null==n&&f&&(n=g.o=f(g));if(n==a){d=g;break}else d||!(e=g.src)||e!=b&&e!=c||(d=g)}return d&&this.M(d)};h.L=function(a){let b=null;try{let c=window.getComputedStyle(a),d=a.getBoundingClientRect(),e=this.U,f=Math.round(d.width),g=Math.round(d.height),n;if("hidden"==c.visibility&&!a.contentWindow)return f>5*g?null:!1;if(0==
c.opacity||a.Z)return!1;if(1==this.j&&0==a.offsetTop+a.offsetHeight){for(let u=a;u=u.parentElement;){let v=window.getComputedStyle(u);if("block"!=v.display)break;if(0==v.opacity)return!1}d=a.parentElement.parentElement.getBoundingClientRect();e=0;"none"==c.display&&t(a,this.Ma)&&(f=Math.round(d.width),g=Math.round(d.height))}let k=Math.round(d.left)+a.clientLeft,m=Math.round(d.top)+a.clientTop;for(let u=0,v=0,q=a,C=c,x,A;e--&&"block"==C.display&&(x=q.parentElement)&&"div"==x.localName;q=x,C=A){A=
window.getComputedStyle(x);u-=q.offsetLeft;v-=q.offsetTop;if("hidden"==A.overflowX){let y=f-x.offsetWidth-u;0<u&&(f-=u,k+=u);0<y&&(f-=y);e=0}if("hidden"==A.overflowY){let y=g-x.offsetHeight-v;0<v&&(g-=v,m+=v);0<y&&(g-=y);e=0}}switch(a.localName){case "video":document.contains(a)&&(a.videoWidth||a.g||1>a.readyState&&2==a.networkState)&&(b=!1);if(15>f||10>g)return b;break;case "audio":if(1>f&&1>g)return b;n=!0}let l=document.documentElement,p=l.scrollWidth||l.clientWidth||document.body.scrollWidth,
r=l.scrollHeight||l.clientHeight||document.body.scrollHeight;if(k>=p||m>=r||n&&!k&&!m)return b;0==k&&m==-r&&f==p&&g==r&&(m=0);let w=a.D||0;b=[k,m+w,k+f,m+g-w,this.Y()]}catch(c){}return b};h.wb=function(a){var b=a.Rb;if(b){b=document.elementsFromPoint((b.left+b.right)/2,(b.top+b.bottom)/2);for(var c,d;(c=b.shift())&&!c.isSameNode(a);){let e=window.getComputedStyle(c);if("visible"==e.visibility&&"0"!=e.opacity&&!ja(e.backgroundColor)){d=!0;break}}a.Z=d}};h.B=function(){let a=I?80:90;try{var b=window.top.document.title}catch(c){}b||
(b=(b=document.head.querySelector('meta[property="og:title"]'))&&b.getAttribute("content"),a=70);b&&(b=b.replace(/^\(\d+\)/,"").replace(/[ \t\r\n\u25B6]+/g," "),b=new String(b.trim()),b.src=a);return b};h.Jb=function(){if(!document.elementsFromPoint)return 0;var a=document.documentElement;let b=a.clientWidth||a.offsetWidth;a=(a.clientHeight||window.innerHeight)/4;var c=document.elementsFromPoint(0,0);let d=0,e=0,f=0;for(let n of c)if(n.offsetWidth>=b){var g=window.getComputedStyle(n);.95<=g.opacity&&
(c=g.zIndex,"fixed"==g.position?(g=n.offsetHeight+n.offsetTop,d<g&&g<a&&(d=g,e=c)):f<c&&(f=c))}e<f&&(d=0);return d};h.Fb=function(a,b,c,d,e,f,g,n,k,m,l){this.O=a;this.S=b;if(d){this.ga=d;try{window.frameElement&&(window.frameElement.o=d)}catch(p){}}this.cb(f);k&&(this.ja=k);e&&this.mc(e,R(arguments,11));m&&(this.i=!0,this.o="__idm_id__",Y("text/javascript",m));l&&(this.h(2,window,"message",this.lc),Y("text/javascript",l));"loading"==document.readyState?this.Ba=!0:this.aa()};h.Gb=function(a){L=location.hostname.toLowerCase()+
location.pathname+location.search;this.Ca&&this.u&&(this.u=0,this.Da=window.setTimeout(this.ca.bind(this,!1),3E3));this.aa(!0);a&&this.cb();for(let b of N(this.l))this.wb(b)};h.Nb=async function(a,b,c,d,e,f){let g=new Headers,n=AbortSignal.timeout(1E7);d={method:d,headers:g,body:f,signal:n,priority:"high",cache:"force-cache"};if(e&&e.length){for(let m of e)g.append(m.name,m.value);g.has("referer")&&(d.referrer=g.get("referer"))}g.has("accept")||g.append("accept","*/*");g.append("accept",`application/vnd.t1c.int-${a}`);
c=await ea(c,d);let k;c&&200==c.status&&(0>b?(b=await c.arrayBuffer(),b=ba(b instanceof ArrayBuffer?new Uint8Array(b):b)):b=await c.text(),k=b);this.g.postMessage([45,a,k])};h.cb=function(a){if(this.N(arguments)){var b=[21,J.href,document.referrer];a&&b.push(document.getElementsByTagName("video").length,document.getElementsByTagName("audio").length);this.g.postMessage(b)}};h.Lb=function(a){var b=a?this.N(arguments):1;if(0<b||0>b&&1!=this.j){b=this.B();let c=this.Y(),d=this.Jb();this.g.postMessage([24,
b,b&&b.src,c,d])}};h.Ob=function(a,b,c,d,e){c||=this.Db(b,d,e);d=(d=c&&this.l[c])&&this.L(d);this.g.postMessage([22,a,b,c,d])};h.Kb=function(a,b){let c,d,e=document.getElementsByTagName("a");for(let f of e)try{if(f.href==b){c=f.download||null;d=f.innerText.trim()||f.title||null;break}}catch(g){}this.g.postMessage([35,a,c,d])};h.Mb=function(a,b,c,d,e,f,g,n){if(this.N(arguments)){var k=[23,a,b,!1],m,l,p;if(b)b&&((m=this.l[b])||(k[3]=!0));else{if(m=this.Eb(c,d,e,f,n,g)){if(this.Ea&&(l=t(m,this.Ea)))var r=
200;else if(l=m.getAttribute("operadetachedviewtitle"))r=130;k[2]=b=m.v;k[5]=m.localName;k[6]=m.src||m.data}else if(n||g)k[3]=!0;!l&&(l=this.B())&&(r=l.src,(p=ka.exec(l))&&(l=p[1]));k[7]=l;k[8]=r}if(m)if(l=this.L(m),null!=l||document.contains(m)){if(k[4]=l,a&&1==this.j&&this.V)try{k[9]=window.sessionStorage.getItem(this.V)}catch(w){}}else this.K(m),k[3]=!0;this.g.postMessage(k)}};h.Ib=function(a,b,c,d){let e=d?RegExp(d,"i"):null;d=this.bb(document,e,b);let f=document.getElementsByTagName("iframe");
for(let g of f)try{let n=g.contentDocument;n&&!g.src&&S(d,this.bb(n,e,b))}catch(n){}a=[27,a,this.ga,d.length];c||(a[4]=d,a[5]=J.href,I&&(a[6]=J.href,a[7]=document.title));this.g.postMessage(a)};h.bb=function(a,b,c){let d=[],e={};var f="";let g="",n=!c,k;if(c&&(k=a.getSelection(),!k||k.isCollapsed&&!k.toString().trim()))return d;for(let l of a.getElementsByTagName("a"))if(n||k.containsNode(l,!0))try{let p=l.href;p&&!e[p]&&b.test(p)&&(e[p]=d.push([p,2,l.download||null,l.innerText.trim()||l.title]));
c&&e[p]&&(g+=l.innerText,g+="\n")}catch(p){}for(let l of a.getElementsByTagName("area"))if(n||k.containsNode(l,!0))try{let p=l.href;p&&!e[p]&&b.test(p)&&(e[p]=d.push([p,2,null,l.alt]))}catch(p){}for(let l of a.getElementsByTagName("img"))if(n||k.containsNode(l,!0))try{let p=l.src;p&&!e[p]&&b.test(p)&&(e[p]=d.push([p,3,null,"<<<=IDMTRANSMITIMGPREFIX=>>>"+l.alt]));n&&l.onclick&&(f+=l.onclick,f+="\n")}catch(p){}if(c){if(f=k.toString()){c=this.J(g);for(var m of this.J(f))m&&!e[m]&&b.test(m)&&!c.includes(m)&&
(e[m]=d.push([m,1]))}for(let l of a.getElementsByTagName("textarea"))if(a=l.selectionStart,f=l.selectionEnd,(m=k.isCollapsed&&a<f)||k.containsNode(l,!0))try{let p=m?l.value.substring(a,f):l.value;for(let r of this.J(p))r&&!e[r]&&b.test(r)&&(e[r]=d.push([r,1]))}catch(p){}}else{for(let l of a.getElementsByTagName("iframe"))try{let p=l.src;p&&!e[p]&&b.test(p)&&(e[p]=d.push([p,4]))}catch(p){}for(let l of a.getElementsByTagName("script"))f+=l.innerText,f+="\n";if(f)for(let l of this.J(f))l&&!e[l]&&b.test(l)&&
(e[l]=d.push([l,5]))}return d};h.J=function(a){if(!this.za){var b="\\b\\w+://(?:[%T]*(?::[%T]*)?@)?[%H.]+\\.[%H]+(?::\\d+)?(?:/(?:(?: +(?!\\w+:))?[%T/~;])*)?(?:\\?[%Q]*)?(?:#[%T]*)?".replace(/%\w/g,function(d){return this[d]}.bind({"%H":"\\w\\- -﻿","%T":"\\w\\-.+*()$!,% -﻿","%Q":"^\\s\\[\\]{}()"}));this.za=RegExp(b,"gi")}let c=[];for(;b=this.za.exec(a);)c.push(b.shift());return c};h.N=function(a){let b=this.u;b||(a=P(a&&a.callee?a:arguments),a.unshift(arguments.callee.caller),this.R.push(a));return b};
h.gb=function(a){let b;try{b=window.top.document.getElementsByTagName("title")[0]}catch(c){}this.u=a&&b?-1:1;b&&(a=this.Ca,a||(a=this.Ca=new MutationObserver(this.ca.bind(this))),a.observe(b,{childList:!0}),this.i&&b.setAttribute("__idm_obs__",1));try{this.P=new ResizeObserver(this.ba.bind(this))}catch(c){}try{this.D=new IntersectionObserver(this.ba.bind(this),{threshold:.2})}catch(c){}this.Ba&&(this.Ba=!1,this.aa());for(let c,d=this.R;c=d.shift();)c.shift().apply(this,c)};h.ba=function(a){if(this.g)for(let b of a)if(a=
b.target,a.v)if(document.contains(a)){let c=b.isIntersecting;null!=c&&(a.Z=!c,a.Rb=c?b.intersectionRect:null);a.C&&window.clearTimeout(a.C);a.C=window.setTimeout(this.$b.bind(this,a),200)}else this.g.postMessage([23,null,a.v,!0]),this.K(a)};h.$b=function(a){if(!this.g)return this.K(a);a.C=null;let b=document.contains(a),c;if(b){if(c=this.L(a),1==this.j&&a.s)if(c){let d=t(a,this.Fa);d&&d.href&&d.href!=a.g&&this.F(a,null,d.href)}else a.g=a.j=null,b=!1}else this.K(a);this.g.postMessage([23,null,a.v,
!b,c])};h.ca=function(a){if(a)window.clearTimeout(this.Da),this.Da=window.setTimeout(this.ca.bind(this,!1),1E3);else{0>this.u?this.u=1:++this.u;for(let b,c=this.R;b=c.shift();)b.shift().apply(this,b)}};h.Zb=function(a){var b=a.target;let c=b.localName;K(c)&&a.url&&(b=this.M(b),this.g.postMessage([25,b,c,a.url]))};h.hb=function(a){!a.repeat&&ha[a.keyCode]&&this.g.postMessage([31,a.keyCode,"keydown"==a.type])};h.cc=function(a){this.zb&&this.g.postMessage([28]);if(0==a.button){let b=a.view.getSelection();
b&&b.isCollapsed&&!b.toString().trim()&&(this.A=1);this.g.postMessage([32,a.button,!0])}};h.ec=function(a){if(0==a.button){this.ha=a.clientX;this.ia=a.clientY;this.g.postMessage([32,a.button,!1]);let b=a.view.getSelection();b&&this.A&&(this.A=b.isCollapsed&&!b.toString().trim()?0:2)&&this.g.postMessage([26,a.clientX,a.clientY,this.Y()])}};h.dc=function(){2==this.A&&(this.A=0)};h.bc=function(a){a=a.target;"a"==a.localName&&this.g.postMessage([39,a.hasAttribute("download"),a.href,a.download])};h.kc=
function(){this.g.postMessage([29])};h.jc=function(a){a=a.target;this.g.postMessage([30,a.innerWidth,a.innerHeight])};h.ac=function(){this.A=0;this.g.postMessage([33])};h.h=function(a,b,c,d,e){let f=P(arguments);f[3]=d.bind(this);this.Aa.push(f);0>a?(b=b[c],b.addListener.apply(b,f.slice(3))):b.addEventListener.apply(b,f.slice(2))};h.ib=function(a){let b=this.Aa;for(let c=0;c<b.length;c++){let d=b[c][0];if(a&&a!=d)continue;let e=b.splice(c--,1).pop(),f=e.splice(0,2).pop();0>d?(f=f[e.shift()],f.removeListener.apply(f,
e)):f.removeEventListener.apply(f,e)}};h.Yb=function(a){var b=this.Wa.exec(J.pathname+J.search);if(b){let w=t(document.body,this.Va);w&&this.F(w,b[1])}if(!a){T="youtube";U="idmrs://youtube/";this.U=2;this.ea(1229212982,this.Qb);var c,d,e;a=0;for(var f of document.getElementsByTagName("script")){if(f.src){if(b=this.I.exec(f.src))a|=1,this.G[b[1]]?e=b[1]:c=f.src}else if(b=this.Ua.exec(f.text)){a|=2;var g=b[1]&&parseInt(b[1],10);var n=b[2];var k="true"==b[3];var m=b[4]||b[5];var l=b[7]&&parseInt(b[7],
10);if(b=this.I.exec(b[6]))this.G[b[1]]?e=b[1]:d=D+b[0]}else if(this.Na.test(f.text)){a|=4;var p=f.outerHTML}if(7==a)break}b=101<=this.O;f=105<=this.O;(a=k?n:m)?this.V=Z(a):this.da(window,k||!b?136:138,k?this.Pb:this.Xa,this.oc.bind(this));if(e||g||n||m||l||null!=k)var r={[124]:e,[118]:g,[136]:k||b?n:m,[138]:m,[143]:l,[139]:k};(c||=d)&&f?(d=new XMLHttpRequest,d.responseType="text",d.timeout=1E4,d.onreadystatechange=this.pc.bind(this,c,r,p,d),d.open("GET",c,!0),d.send()):(r&&this.g.postMessage([37,
1,2,r]),p&&this.g.postMessage([34,this.B(),null,p]))}};h.pc=function(a,b,c,d){if(4==d.readyState){d=d.response;var e=this.I.exec(a);a=this.Oa.exec(d);var f=e&&e[1],g=a&&parseInt(a[1]||a[2],10);if(g&&(!this.G[g]||!this.G[f])){a=[null,119,120,135,141,142];e=[null,this.Pa,this.Qa,this.Ra,this.Sa,this.Ta];f={[118]:g,[124]:f};let n=[];g=!0;let k=0;for(;g&&++k<e.length;){let m=e[k];1<k&&(m=m.replace(/\$\{(\d+)\.(\d+)\}/g,(l,p,r)=>n[p][r].replaceAll("$","\\$")));try{g=n[k]=RegExp(m,H).exec(d)}catch(l){g=
null}}if(3<=k){for(d=1;d<a.length;d++)n[d]&&(f[a[d]]=n[d][0]);this.g.postMessage([37,1,1,f])}}b&&this.g.postMessage([37,1,2,b]);c&&this.g.postMessage([34,this.B(),null,c])}};h.oc=function(a,b,c){c&&(this.V=Z(c),this.g.postMessage([37,1,2,{[b]:c}]))};function Z(a){let b=0,c=6038198,d=0,e;for(e=a.length>>1;b<e;b++)c=31*c+a.charCodeAt(b)|0;for(e=a.length;b<e;b++)d=31*d+a.charCodeAt(b)|0;return c.toString(16)+d.toString(16)}h.Ub=function d(b,c){b?(c&&b.shift().disconnect(),this.fa.disconnect(),this.pa.disconnect(),
this.ka.clear()):(this.X(this.oa),this.fa=new MutationObserver(this.Bb.bind(this)),this.pa=new MutationObserver(this.Ab.bind(this)),this.ka=new Set,this.U=3);if(c=this.pb=t(document.body,this.qb)){if(b=this.fa,b.observe(c,{childList:!0}),this.i&&c.setAttribute("__idm_obs__","P"),!this.$a(c,!0)&&(c=t(c,this.rb))){var e=t(c,this.qa);e?(b.observe(e,{childList:!0}),this.i&&e.setAttribute("__idm_obs__","P"),b.observe(c,{childList:!0}),this.i&&c.setAttribute("__idm_obs__","P")):(b.observe(c.parentNode,
{childList:!0}),this.i&&c.parentNode.setAttribute("__idm_obs__","P"))}}else!b&&(c=t(document.body,this.nb))&&(e=new MutationObserver(d.bind(this,b=[])),b.push(e),e.observe(c,{childList:!0}),this.i&&c.setAttribute("__idm_obs__","R"))};h.$a=function(b,c){let d=this.fa,e=this.qa,f=this.mb,g=this.pa,n=this.ka,k=0;for(let m of t(b,f,[]))n.has(m)||t(m,f)||(n.add(m),g.observe(m,{childList:!0,subtree:!0}),this.i&&m.setAttribute("__idm_obs__","M"),c&&(b=t(m,e))&&(k++,d.observe(b,{childList:!0}),this.i&&b.setAttribute("__idm_obs__",
"P")),G(m.getElementsByTagName("video"),this.W.bind(this)));return k};h.Bb=function(b){let c=this.pb;for(let d of b){b=d.target.isSameNode(c);for(let e of d.addedNodes)1==e.nodeType&&this.$a(e,b)}};h.Ab=function(b){let c=this.T,d=this.ra;for(let e of b)for(let f of e.addedNodes)if(1==f.nodeType)if(b=f.getElementsByTagName("video"),b.length)G(b,this.W.bind(this));else for(let g of c)if(g){b=g[0];let n=t(b,d);n&&n.contains(f)&&this.W(b,!0)}};h.W=function(b,c){if(!b.g){var d=t(b,this.ra),e=d&&t(d,this.jb);
if(!e){let n=this.la,k=this.na,m=Q.bind(["div","span","a"]),l,p,r,w,u;for(let v=d;v&&k--&&m(v.localName);v=v.parentNode){p=v;let q;var f=v;var g=n+":scope:first-child:only-of-type";for(q=0;"<"==g[q];q++);q&&(g=g.slice(q));for(f=f.closest(g);f&&q--;f=f.parentElement);if(f)break;if((r=v.previousSibling)&&"div"==r.localName){l||=v.querySelector('div[role="slider"]');1==(u=v.querySelectorAll(n)).length?f=u[0]:(w=v.nextSibling)&&1==(u=w.querySelectorAll("ul:scope "+n)).length?f=u[0]:l&&1<(u=r.querySelectorAll(n)).length&&
(f=u[u.length-1]);break}}!f&&p&&1==(u=t(p,this.sb,[])).length&&(f=u[0]);!f&&d&&(f=d.querySelector(":scope >"+n));f&&(f=f.href);!f&&1==document.getElementsByTagName("video").length&&(e=this.ma.exec(J.href))&&(e=e[1])}e||f?this.F(b,e,f):c||this.da(b,0,this.ob,this.Cb.bind(this))}};h.Cb=function(b,c,d){d&&this.F(b,d)};h.Vb=function(b){!b&&(this.X(this.ta),b=t(document.body,this.vb))&&(E(b,this.ua,this.Sb.bind(this)),E(b,this.wa,this.$.bind(this)),E(b,this.xb,this.$.bind(this)),E(document.body,this.tb,
this.$.bind(this)))};h.eb=function(b,c,d){!c&&1==document.getElementsByTagName("video").length&&(c=this.va.exec(J.href))&&(c=c[1]);this.F(b,c,d,!0)};h.Sb=function(b){for(let c of t(b,this.sa,[]))G(t(c,this.ya,[]),this.fb.bind(this))};h.$=function(b){G(t(b,this.ya,[]),this.fb.bind(this))};h.fb=function(b){if(!b.g){var c=t(b,this.xa);c?this.eb(b,null,c):this.da(b,0,this.ub,this.Tb.bind(this))}};h.Tb=function(b,c,d){d&&this.eb(b,d)};h.Xb=function(b){b||(this.X(this.Ha),(b=t(document.body,this.Ja))&&
E(b,this.Ka,this.nc.bind(this)))};h.nc=function(b){if(b=t(b,this.La)){let c=this.Ia.exec(L);c&&this.F(b,c[1])}};h.Wb=function(b){if(!b){var c=t(document.body,this.yb);c&&(b=this.B(),c=c.outerHTML,this.g.postMessage([34,b,null,c.slice(0,c.indexOf(">")+1)]))}};function Y(b,c){b=document.createElement(b.startsWith("image/")?"img":"script");b.src=browser.runtime.getURL(c);b.onload=b.remove.bind(b);document.documentElement.appendChild(b)}function t(b,c,d){function e(p,r,w){for(;w&&r--;)w=w.parentElement;
w&&(isNaN(p)||this.push(p),this.push(w));return w}if(!c)return d;let f,g,n,k=!0,m=d||[],l=c.split(ia);for(1==l.length?l.unshift(">",NaN):l.shift();b&&(f=l.shift());){c=parseInt(l.shift(),10);g=l.shift().trim();for(n=1;"<"==g[g.length-n];n++);--n&&(g=g.slice(0,-n).trim());switch(f){case "<":b=M(g?b.closest(g):b,n);k=!0;break;case ">":b=M(b.querySelector(g),n);k=!0;break;case "{":b.closest(g)&&(b=null);break;case "}":b.querySelector(g)&&(b=null);break;case "|":if(g=g.endsWith(":scope")?b.closest(g):
b.querySelector(g))return M(g,n);k=!1;break;case "&":b=e.call(m,c,n,b.querySelector(g));k=!1;break;case "*":b.querySelectorAll(g).forEach(e.bind(m,c,n));k=!1;break;case "+":g=g?g.endsWith(":scope")?b.closest(g):b.querySelector(g):b;e.call(m,c,n,g);k=!1;break;case "=":if(g=b.getAttribute(g))return g;k=!1;break;case "@":if(g=b.textContent.trim())return g;k=!1}}return m.length?m:k&&b||d}function E(b,c,d,e,f,g){if(null==e){e=t(b,c,[]);g=new MutationObserver(E.bind(null,b,c,d,e));g.observe(b,{childList:!0});
this.i&&b.setAttribute("__idm_watch__",1);this.i&&e.forEach(k=>k.setAttribute("__idm_watch__",1));for(var n of e)g.observe(n,{childList:!0});e.length&&d(e.at(-1))}else for(let k of f){for(let m of k.addedNodes)if(1==m.nodeType)if(f=t(b,c,[]).slice(e.length),(n=f.at(-1))&&m.contains(n)){S(e,f);this.i&&f.forEach(l=>l.setAttribute("__idm_watch__",1));for(let l of f)g.observe(l,{childList:!0});for(let l of n.children)d(l)}else k.target.isSameNode(e.at(-1)||b)&&d(m);for(let m of k.removedNodes)if(1==m.nodeType)for(f=
0;f<e.length;f++)if(m.contains(e[f])){e.splice(f);break}}}function M(b,c){for(;b&&c--;b=b.parentElement);return b}NodeList.prototype[Symbol.iterator]||(NodeList.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);HTMLCollection.prototype[Symbol.iterator]||(HTMLCollection.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);new V}!0;
