export const jsonData = {
    "page_1": {
        "[0, 709, 29, 902]": "NGHỀ NGHIỆP TRÍ TUỆ NHÂN TẠO",
        "[53, 95, 290, 892]": "Cuộc Cách Mạng Kiểm Toán AI:\nCác Chuyên Gia Công Nghệ Đang\nTrở Thành Người Bảo Vệ cho\nTrách Nhiệm Giải Trình Thuật Toán"
    },
    "page_2": {
        "[18, 672, 45, 902]": "THỊ TRƯỜNG AI",
        "[59, 94, 86, 846]": "5. Pro AI: Công Cụ Thông Minh Nhất Cho Các Nhà Sáng Lập Tập Trung Huy Động Vốn",
        "[114, 230, 285, 750]": "ProAI\nTính năng\nGiá\nCông cụ tạo Kế hoạch kinh doanh AI\nĐạt được thành công với các kế hoạch kinh doanh, nghiên cứu và chiến lược tùy chỉnh được tạo ra bằng AI, dựa trên kinh nghiệm từ hơn 3.600 dự án khách hàng.\nTạo Kế hoạch kinh doanh\nGoogle AI\nOpenAI",
        "[291, 95, 331, 902]": "Pro AI thường được tích hợp vào các nền tảng lớn hơn và tập trung cao độ vào việc giúp doanh nghiệp huy động vốn. Nó sử dụng dữ liệu độc quyền, nghiên cứu thị trường bên thứ ba và AI để tạo ra các kế hoạch kinh doanh thuyết phục, các bộ hồ sơ gọi vốn (pitch decks) và các chiến lược tiếp cận nhà đầu tư.",
        "[343, 95, 390, 902]": "Nó không chỉ tạo ra các kế hoạch; nó đi sâu vào chi tiết. Từ dự báo tài chính chi tiết (Báo cáo kết quả kinh doanh (P&L), bảng cân đối kế toán, lưu chuyển tiền tệ) đến việc kết nối nhà đầu tư và hỗ trợ định giá, Pro AI hoạt động như một nhà tư vấn kỹ thuật số. Bạn có thể xuất các mô hình Excel, nhận đề xuất cải thiện bài thuyết trình gọi vốn và thậm chí mô phỏng các buổi Hỏi & Đáp với nhà đầu tư.",
        "[402, 95, 432, 902]": "Pro AI mang lại lợi ích cho các startup giai đoạn tăng trưởng đang tìm cách trình bày các câu chuyện hấp dẫn nhà đầu tư, dựa trên dữ liệu mà không cần thuê một công ty tư vấn đắt tiền.",
        "[444, 95, 474, 255]": "Liên kết",
        "[540, 95, 567, 755]": "6. Frederick: Thông Tin Chi Tiết về Bán Hàng và Khách Hàng Dựa trên AI",
        "[584, 230, 769, 749]": "Frederick AI\nTài nguyên\nGiá\nLiên hệ\nĐăng nhập\nĐăng ký\nFrederick AI hiện đang trong giai đoạn beta\nĐồng đội AI cho startup của bạn\nNghiên cứu, lập kế hoạch và ra mắt dự án tiếp theo của bạn.\nDùng thử miễn phí\nTham gia Discord",
        "[785, 95, 825, 902]": "Mặc dù Frederick không phải là công cụ lập kế hoạch kinh doanh truyền thống, nhưng nó đóng vai trò quan trọng trong việc xác thực các giả định dùng để lập kế hoạch. Đây là một nền tảng tương tác khách hàng dựa trên AI, cung cấp những hiểu biết sâu sắc về hành vi của khách hàng, những gì họ phản hồi và cách các đội ngũ bán hàng có thể tối ưu hóa hoạt động tiếp cận.",
        "[837, 95, 867, 902]": "Với các tính năng như nuôi dưỡng khách hàng tiềm năng tự động, tin nhắn được cá nhân hóa và theo dõi hành vi bán hàng, Frederick giúp các doanh nghiệp chốt được nhiều giao dịch hơn và giữ chân khách hàng hiệu quả hơn.",
        "[879, 95, 920, 902]": "Thông tin tình báo khách hàng theo thời gian thực là vô giá khi xây dựng kế hoạch thâm nhập thị trường, mô hình doanh thu và dự báo bán hàng. Về nhiều mặt, nó là người bạn đồng hành hoàn hảo với các công cụ khác trong danh sách này. Nó đảm bảo các giả định của bạn được đặt nền tảng dựa trên",
        "[928, 95, 958, 255]": "Liên kết",
        "[958, 888, 981, 915]": "39"
    },
    "page_3": {
        "[18, 672, 45, 902]": "THỊ TRƯỜNG AI",
        "[59, 94, 98, 747]": "3. BizPlanner AI: Giúp Việc Lập Kế Hoạch Kinh Doanh Dễ Dàng Cho Người Mới Bắt Đầu",
        "[104, 230, 292, 750]": "BizPlanner.AI\nSản phẩm\nMẫu\nGiá\nBlog\nLiên hệ\nĐăng nhập\n#1 Công cụ tạo Kế hoạch kinh doanh AI\nViết kế hoạch kinh doanh của bạn trong vài phút, không phải vài ngày\nBỏ qua sự khó khăn khi viết kế hoạch kinh doanh từ đầu. Công cụ tạo kế hoạch kinh doanh AI của chúng tôi sẽ tạo ra một kế hoạch toàn diện, sẵn sàng cho nhà đầu tư, bao gồm mô hình kinh doanh, thị trường mục tiêu, dự báo tài chính, và nhiều hơn nữa, giúp bạn tập trung vào việc phát triển doanh nghiệp.\nKế hoạch kinh doanh\nKế hoạch tiếp thị\nĐối tượng mục tiêu\nPhân tích SWOT\nPhân tích đối thủ cạnh tranh\nDự báo tài chính\nXu hướng ngành\nSố liệu thống kê ngành\nQuy định liên quan\nCác bước tiếp theo được đề xuất",
        "[304, 95, 345, 902]": "BizPlanner AI là một công cụ dễ tiếp cận, dễ sử dụng, lý tưởng cho các nhà sáng lập giai đoạn đầu. Không giống như các nền tảng khác yêu cầu đầu vào chuyên sâu hoặc kiến thức lập kế hoạch trước đó, BizPlanner sử dụng bảng câu hỏi hướng dẫn đơn giản để biến ý tưởng thành các kế hoạch kinh doanh hoàn chỉnh.",
        "[357, 95, 402, 902]": "Giao diện trực quan của nó đặc biệt hấp dẫn đối với các doanh nhân độc lập (solopreneurs) hoặc các nhà sáng lập lần đầu. Công cụ này bao gồm tất cả các yếu tố cơ bản: chiến lược tiếp thị, phân tích đối thủ cạnh tranh và dự báo tài chính thực tế. Các kế hoạch có thể được tải xuống dưới dạng Word hoặc PDF, dễ dàng chỉnh sửa và chia sẻ.",
        "[415, 95, 446, 902]": "BizPlanner AI cũng thân thiện với ngân sách, thường cung cấp tùy chọn mua một lần thay vì các gói đăng ký tốn kém, điều này thu hút các chủ doanh nghiệp nhỏ cần tạo ra tác động mà không cần chi tiêu quá lớn.",
        "[460, 95, 496, 260]": "Liên kết",
        "[513, 95, 540, 866]": "4. Công Cụ AI của Upmetrics: Trung Tâm Toàn Diện về Lập Kế Hoạch & Dự Báo",
        "[545, 230, 740, 750]": "upmetrics\nSản phẩm\nGiải pháp\nDịch vụ\nTài nguyên\nGiá\nEN\nĐăng nhập\nCông cụ tạo Kế hoạch kinh doanh AI+\nTạo kế hoạch kinh doanh của bạn trong vài phút với Trợ lý AI của chúng tôi\nTrả lời một vài câu hỏi riêng biệt về doanh nghiệp của bạn và nhận kế hoạch kinh doanh trong vòng chưa đầy 10 phút. Đơn giản là như vậy.\nHãy bắt đầu lập kế hoạch!\nTuyệt vời ✶✶✶✶✶ 4.9/5.0 Capterra",
        "[752, 95, 800, 902]": "Upmetrics không chỉ là một công cụ tạo kế hoạch kinh doanh—nó là một trung tâm lập kế hoạch và dự báo tài chính toàn diện, được thiết kế cho các doanh nhân cần sự chính xác, rõ ràng và tốc độ. Nó tinh giản hành trình từ ý tưởng kinh doanh đến bài thuyết trình cho nhà đầu tư bằng các công cụ hỗ trợ bởi AI, giúp đơn giản hóa các nhiệm vụ lập kế hoạch phức tạp và làm cho việc mô hình hóa tài chính dễ tiếp cận hơn nhiều.",
        "[805, 95, 858, 902]": "Upmetrics thực sự nổi bật trong khả năng dự báo tài chính được tăng cường bởi AI. Thay vì dựa vào phỏng đoán hoặc các mẫu chung chung, người dùng nhận được các đề xuất thông minh cho các dự báo, cùng với các tùy chọn tích hợp nền tảng kế toán để đạt độ chính xác cao hơn nữa. Điều này giúp giảm lỗi và củng cố độ tin cậy, vốn đặc biệt quan trọng khi gọi vốn từ nhà đầu tư.",
        "[864, 95, 929, 902]": "Một trong những tính năng sáng tạo nhất của nó là AI Co-Pilot (Đồng Phi công AI), một trợ lý đối thoại hoạt động như một cố vấn ảo. Nó trả lời các câu hỏi liên quan đến kế hoạch theo thời gian thực và đưa ra hướng dẫn về chiến lược kinh doanh, mang lại cảm giác như có một cố vấn giàu kinh nghiệm luôn sẵn sàng. Ngoài ra, nền tảng này còn bao gồm thư viện hơn 400 mẫu dành riêng cho ngành, công cụ tạo pitch deck được hỗ trợ bởi AI và các công cụ cộng tác để hỗ trợ lập kế hoạch giữa các đội nhóm.",
        "[929, 95, 963, 259]": "Liên kết",
        "[958, 888, 981, 915]": "38"
    },
    "page_4": {
        "[0, 710, 41, 902]": "NGHỀ NGHIỆP AI",
        "[96, 97, 123, 497]": "Tái định nghĩa Nghề Kiểm toán",
        "[135, 97, 150, 429]": "Vượt xa Tuân thủ Truyền thống",
        "[155, 97, 214, 577]": "Kiểm toán truyền thống tập trung vào tính chính xác tài chính và sự tuân thủ quy định. Kiểm toán AI đòi hỏi một phương pháp tiếp cận khác biệt căn bản: đánh giá các hệ thống học hỏi, thích ứng và đưa ra quyết định theo những cách không thể dự đoán hoặc kiểm soát hoàn toàn. Điều này đòi hỏi những phương pháp luận mới kết hợp khoa học máy tính, thống kê, khoa học xã hội và đạo đức.",
        "[220, 97, 290, 577]": "Các kiểm toán viên AI phát triển các khuôn khổ thử nghiệm để tìm kiếm sai lệch thuật toán, các chỉ số công bằng có thể áp dụng trong các bối cảnh khác nhau, và các tiêu chuẩn tài liệu giúp các hệ thống AI có thể giải thích được cho các bên liên quan không chuyên về kỹ thuật. Họ đang xây dựng cơ sở hạ tầng cho trách nhiệm giải trình thuật toán từ đầu.",
        "[302, 97, 317, 399]": "Kho Vũ Khí Kỹ Thuật",
        "[322, 97, 331, 577]": "Các kiểm toán viên AI hiện đại sử dụng các công cụ và kỹ thuật tinh vi:",
        "[347, 124, 388, 577]": "Các Khuôn khổ Phát hiện Sai lệch: Các thư viện như AI Fairness 360 của IBM và What-If Tool của Google cho phép kiểm tra có hệ thống đối với tác động khác biệt trên các nhóm được bảo vệ.",
        "[399, 124, 440, 577]": "Các Nền tảng Khả năng Giải thích: Các công cụ như SHAP, LIME và Integrated Gradients giúp kiểm toán viên hiểu cách các mô hình đưa ra quyết định và xác định các điểm lỗi tiềm ẩn.",
        "[451, 124, 496, 577]": "Kiểm thử Đối kháng: Các kỹ thuật mượn từ an ninh mạng để kiểm tra tính mạnh mẽ của mô hình và xác định các trường hợp ngoại lệ nơi các hệ thống có thể thất bại thảm hại.",
        "[506, 124, 554, 577]": "Theo dõi Nguồn gốc Dữ liệu: Các nền tảng như DataHub và Apache Atlas cho phép kiểm toán viên theo dõi cách dữ liệu huấn luyện luân chuyển qua các quy trình phức tạp và xác định các điểm nhiễm bẩn tiềm ẩn.",
        "[565, 124, 606, 577]": "Tạo Dữ liệu Tổng hợp: Các công cụ tạo ra các bộ dữ liệu thử nghiệm có thể kiểm tra các chế độ lỗi cụ thể mà không làm ảnh hưởng đến quyền riêng tư hoặc thông tin độc quyền.",
        "[621, 97, 652, 577]": "Các công cụ này chuyển đổi kiểm toán AI từ đánh giá chủ quan thành đánh giá nghiêm ngặt, dựa trên bằng chứng.",
        "[674, 96, 722, 545]": "Xây Dựng Các Khuôn Khổ Kiểm Toán Phù Hợp Với Ngành",
        "[734, 97, 749, 423]": "Đánh giá Nhạy cảm với Bối cảnh",
        "[754, 97, 814, 577]": "Các chuyên gia AI kỳ cựu mang kiến thức ngành quan trọng vào việc thiết kế kiểm toán. Họ hiểu rằng một thuật toán tuyển dụng đòi hỏi các tiêu chí đánh giá khác với một hệ thống chẩn đoán y tế hoặc mô hình cho vay tài chính. Các khuôn khổ của họ tính đến các rủi ro đặc thù của lĩnh vực, yêu cầu quy định và kỳ vọng của các bên liên quan.",
        "[819, 97, 884, 577]": "Một cựu kỹ sư fintech chuyển sang làm kiểm toán viên có thể thiết kế các bài kiểm tra dò tìm các mô hình cho vay phân biệt đối xử, đồng thời đảm bảo tuân thủ luật cho vay công bằng. Một chuyên gia AI kỳ cựu trong lĩnh vực chăm sóc sức khỏe có thể tập trung vào độ chính xác chẩn đoán trên các nhóm nhân khẩu học, đồng thời duy trì các biện pháp bảo vệ quyền riêng tư của bệnh nhân.",
        "[960, 39, 983, 67]": "42"
    },
    "page_5": {
        "[0, 710, 41, 902]": "NGHỀ NGHIỆP AI",
        "[50, 96, 73, 552]": "Một Biên Giới Mới về Trách Nhiệm Giải Trình AI",
        "[86, 97, 200, 577]": "Trên khắp các phòng họp và văn phòng chính phủ trên toàn thế giới, một cuộc cách mạng thầm lặng đang hình thành. Các chuyên gia AI dày dạn kinh nghiệm, bao gồm các cựu kỹ sư học máy, nhà khoa học dữ liệu và quản lý sản phẩm, đang đổi vai trò xây dựng mô hình của họ để làm một điều hoàn toàn khác: trở thành người giám sát các hệ thống mà họ từng tạo ra. Lĩnh vực kiểm toán AI mới nổi này đại diện không chỉ là một sự chuyển đổi nghề nghiệp; đó là sự tái hình dung căn bản về cách xã hội đảm bảo việc triển khai AI có trách nhiệm.",
        "[206, 97, 290, 577]": "Thời điểm này không thể quan trọng hơn. Khi các hệ thống AI đưa ra các quyết định về phê duyệt khoản vay, quy trình tuyển dụng, chẩn đoán y tế và tuyên án hình sự, nhu cầu giám sát nghiêm ngặt chưa bao giờ cấp bách hơn thế. Tuy nhiên, các phương pháp kiểm toán truyền thống tỏ ra thiếu sót khi đối diện với mạng thần kinh, mô hình tổng hợp và các quy trình dữ liệu phức tạp. Đó là lúc kiểm toán viên AI xuất hiện, một chuyên gia nói được cả ngôn ngữ của thuật toán và ngữ pháp của trách nhiệm giải trình.",
        "[296, 97, 366, 577]": "Sự thay đổi này phản ánh một ngành công nghiệp đang trưởng thành, công nhận rằng việc xây dựng hệ thống AI chỉ là một nửa của phương trình. Nửa còn lại liên quan đến việc đảm bảo các hệ thống này hoạt động công bằng, minh bạch và có đạo đức trong các bối cảnh thế giới thực. Các cựu nhà phát triển từng tối ưu hóa độ chính xác giờ đây đang tối ưu hóa niềm tin.",
        "[388, 96, 411, 571]": "Tại Sao Các Chuyên Gia AI Lại Chọn Con Đường Kiểm Toán",
        "[424, 97, 439, 353]": "Sự Thức Tỉnh về Đạo Đức",
        "[444, 97, 541, 577]": "Nhiều chuyên gia AI đạt đến khoảnh khắc nhận ra sau nhiều năm triển khai các mô hình vào sản xuất. Họ chứng kiến tận mắt cách các thuật toán tưởng chừng trung lập có thể duy trì sự thiên vị, cách các mục tiêu tối ưu hóa có thể không phù hợp với giá trị con người, và cách nợ kỹ thuật trong các hệ thống AI có thể tích tụ thành tác hại xã hội. Việc chuyển sang kiểm toán thể hiện mong muốn trở thành một phần của giải pháp thay vì vô tình góp phần gây ra vấn đề.",
        "[546, 97, 616, 577]": "Những người khác bị thu hút bởi thách thức trí tuệ. Kiểm toán các hệ thống AI đòi hỏi phải đảo ngược kỹ thuật các kiến trúc phức tạp, hiểu được nguồn gốc dữ liệu và phát hiện các mô hình sai lệch hoặc thao túng tinh vi. Đó là công việc thám tử đòi hỏi cả sự tinh vi kỹ thuật và bản năng điều tra.",
        "[629, 97, 652, 572]": "Nhu Cầu Thị Trường và Áp Lực Quy Định",
        "[658, 97, 742, 577]": "Bối cảnh quy định đang thúc đẩy nhu cầu chưa từng có đối với kiểm toán viên AI. Đạo luật AI của EU, các hướng dẫn liên bang mới nổi của Hoa Kỳ và các yêu cầu quản trị doanh nghiệp đang tạo ra một loại hình chuyên môn mới. Các công ty như Anthropic, OpenAI và Google đang thành lập các nhóm an toàn AI nội bộ với nhân sự là các cựu kỹ sư. Các công ty tư vấn đang triển khai các dịch vụ kiểm toán AI, và các cơ quan quản lý đang tuyển dụng các nhà công nghệ để phát triển các khuôn khổ tuân thủ.",
        "[748, 97, 818, 577]": "Ở New York, Luật Địa phương 144 yêu cầu kiểm toán thuật toán đối với các công cụ tuyển dụng. Ở California, Đạo luật Cơ hội Công bằng đòi hỏi sự minh bạch trong việc ra quyết định tự động. Những quy định này không chỉ yêu cầu tuân thủ, mà còn yêu cầu các chuyên gia thực sự có thể đánh giá các hệ thống AI về tính công bằng, độ chính xác và sai lệch.",
        "[831, 97, 854, 542]": "Sự Giao Thoa giữa Tác động Kỹ thuật và Xã hội",
        "[859, 97, 914, 577]": "Kiểm toán AI mang lại sự kết hợp độc đáo giữa tính nghiêm ngặt kỹ thuật và mục đích xã hội. Các kiểm toán viên kiểm tra kiến trúc mô hình, truy tìm nguồn gốc dữ liệu và phân tích đầu ra thuật toán, nhưng họ làm điều đó để phục vụ các mục tiêu xã hội rộng lớn hơn.",
        "[919, 97, 944, 577]": "Họ không chỉ gỡ lỗi mã; họ đang gỡ lỗi các hệ thống quyền lực và khả năng tiếp cận.",
        "[958, 888, 981, 915]": "41"
    }
};