export const jsonData = {
  "page_1": {
    "[16, 276, 126, 882]": "ALBA",
    "[31, 26, 73, 267]": "Trong 3 tháng",
    "[19, 909, 29, 981]": "Thứ 2 và Thứ 4",
    "[32, 908, 43, 981]": "Phát hành Thứ Năm hàng tuần",
    "[45, 910, 56, 981]": "Số ra ngày 25 tháng 9",
    "[59, 922, 69, 981]": "Số 660",
    "[73, 27, 124, 264]": "Giảm được 20 gậy!",
    "[79, 905, 110, 977]": "Giá đặc biệt: 600 Yên",
    "[115, 663, 128, 816]": "TROSS-VIEW",
    "[119, 900, 143, 979]": "Trải nghiệm! Cảm nhận!\nThực hành ngay!!",
    "[130, 27, 172, 178]": "Phương pháp\ntuyệt vời",
    "[171, 16, 298, 973]": "Phá mốc 80 gậy trong 3 tháng",
    "[344, 982, 597, 990]": "Xuất bản và Phát hành ngày 1 tháng 9 năm Heisei 26 (Phát hành Thứ Năm, tuần thứ 2 & 4 hàng tháng). Tập 20, Số 26. Được cấp phép bưu phẩm loại 3 ngày 16 tháng 5 năm Heisei 2 năm.",
    "[346, 649, 410, 966]": "Tập hợp những lời giải tối thượng\nthay đổi cuộc đời chơi golf của bạn",
    "[379, 31, 442, 281]": "Có thật đấy!\nĐiểm chung của những người\nđột nhiên chơi giỏi hơn",
    "[463, 719, 508, 946]": "Ngay cả cú swing cũng cần 'danshari' (tối giản hóa)\nCách loại bỏ kỹ thuật không cần thiết",
    "[486, 39, 552, 258]": "Cú đánh tee:\nchọn giữa gậy driver (1W) không bị lệch trái\nhoặc gậy fairway wood (FW) bắt bóng tốt",
    "[551, 718, 596, 944]": "Ngay cả các tay golf chuyên nghiệp hàng đầu cũng có vấn đề tương tự!\nBiện pháp phòng tránh swing chậm",
    "[595, 38, 669, 334]": "Cú putt dài:\nhãy nghĩ \"đằng nào cũng 3 putt\"\nvà luôn cố gắng đánh bóng đi quá lỗ",
    "[601, 350, 638, 433]": "COVERT",
    "[639, 691, 686, 942]": "Luôn đánh trúng điểm vàng mọi lúc mọi nơi!\nRèn luyện \"trực giác đánh bóng\"",
    "[748, 32, 810, 257]": "Chúng tôi đã đo tốc độ đầu gậy\ncủa những người nổi tiếng\nvà các vận động viên hàng đầu!",
    "[816, 50, 853, 235]": "Endo (Gamba Osaka)\n49.3m/s",
    "[850, 456, 860, 630]": "Hiện tại là mạnh nhất thế giới",
    "[858, 49, 893, 235]": "Đô vật chuyên nghiệp - Tanahashi\n46.7m/s",
    "[866, 452, 950, 755]": "Cú swing của\nMcIlroy",
    "[888, 810, 898, 878]": "Rory Mcllroy",
    "[899, 52, 936, 235]": "Người mẫu - Moe Oshikiri\n33.1m/s",
    "[950, 131, 962, 161]": "và các nội dung khác"
  },
  "page_2": {
    "[99, 114, 136, 311]": "Tiểu luận",
    "[137, 119, 166, 241]": "Tiểu luận A",
    "[174, 161, 185, 203]": "[Kỳ 29]",
    "[528, 295, 591, 759]": "\"Golf Family Festa\" tại thành phố Kanuma, tỉnh Tochigi, nơi trẻ em nô đùa trên bãi cỏ",
    "[608, 93, 725, 804]": "Sân golf",
    "[721, 34, 843, 915]": "đã trở thành công viên",
    "[849, 151, 930, 921]": "Bạn có còn nhớ lần đầu tiên đặt chân lên sân golf không? Chắc hẳn nhiều người đã cảm thấy xúc động sâu sắc khi bước ra khỏi nhà câu lạc bộ và nhìn thấy tấm thảm xanh trải rộng trước mắt. Đối với những đứa trẻ nhạy cảm, cảm xúc này càng mạnh mẽ hơn. Tuy nhiên, thực tế là cảm xúc đó gần như chỉ dành riêng cho các golfer. Chúng tôi muốn không gian sang trọng của sân golf được chia sẻ rộng rãi hơn, bất kể người ta có chơi golf hay không. Một nỗ lực như vậy đã được thực hiện vào một ngày trong kỳ nghỉ hè.",
    "[931, 396, 941, 629]": "Phỏng vấn và viết bài: Kato Jump. Ảnh: Aritaka Tadafumi",
    "[966, 99, 981, 215]": "167 ALBA TROSS-VIEW"
  },
  "page_3": {
    "[196, 751, 211, 765]": "Lực",
    "[199, 672, 381, 872]": "\"Đội Thám Hiểm Ếch!\" Có lẽ là đồ bơi chăng? Hay là vì chơi dưới nước quá vui nên bọn trẻ cởi phăng áo. Dù sao đi nữa, những cậu bé này chỉ mặc quần lót, bì bõm lội trong hồ tạo thành những gợn sóng. Trên một chiếc đĩa xốp trắng có một chú ếch nhỏ thật. Lấy chú ếch đó làm đội trưởng, lũ trẻ đang cười đùa rôm rả trong nước. Đó là ngày 18 tháng 8, tại thành phố Kanuma, tỉnh Tochigi. Nhiệt độ cảm nhận được ngày hôm đó là: \"Chắc phải gần 35 độ đấy.\"",
    "[382, 672, 434, 873]": "Người đàn ông quản lý khu vực hồ nói. Vào một ngày hè nóng bức, giữa những bãi cỏ phản chiếu ánh nắng mặt trời lấp lánh, lũ trẻ đang tự do vui chơi theo cách của mình.",
    "[435, 673, 469, 872]": "\"Trông cứ như công viên ở nước ngoài ấy nhỉ. Kiểu như Central Park ấy.\"",
    "[471, 341, 571, 872]": "Tôi buột miệng nói tên một công viên ở New York mà tôi chưa từng đến. Khi được hỏi, ông Fukushima Hanji vừa cười lớn, vừa để mồ hôi nhỏ giọt xuống tay áo sơ mi Hawaii của mình. \"Đúng thế thật. Chắc không ai nghĩ đây là sân golf đâu nhỉ.\" Đúng vậy. Đây chính là Kanuma 72 Country Club ở thành phố Kanuma, tỉnh Tochigi. Cái hồ kia chính là hồ của sân golf, nơi mà bóng golf rơi xuống thường gây ra sự bực bội. Vậy mà ở đó, lũ trẻ chỉ mặc quần lót và đang say sưa chơi đùa với nước. Chuyện gì đang xảy ra vậy? Điều gì đang diễn ra tại sân golf này?",
    "[716, 159, 747, 245]": "*",
    "[802, 37, 850, 248]": "Hệ thống phun nước (sprinkler) vốn được lắp đặt để chăm sóc cỏ, nay trở thành món đồ chơi lý tưởng cho lũ trẻ",
    "[856, 439, 943, 757]": "Tắm nước như đang nhảy múa quanh vòi phun nước, cười đùa thật lớn",
    "[970, 767, 984, 907]": "ALBA TROSS-VIEW 168"
  },
  "page_4": {
    "[201, 810, 249, 981]": "Sự kiện này được gọi là \"Golf Family Festa\" (Lễ hội Gia đình Golf). Nó được tổ chức bởi Hiệp hội Sân golf Khu vực Kanuma và được hỗ trợ bởi Thành phố Kanuma, Hiệp hội Sản phẩm Du lịch Kanuma, v.v.",
    "[249, 810, 415, 981]": "Tóm lại, đây là một \"lễ hội\" mở cửa sân golf cho trẻ em và người dân địa phương. Tuy nhiên, đối với những người quen thuộc với cảnh tượng sân golf thông thường, đây vẫn là một cảnh tượng kỳ lạ. Có một cô bé đang lộn nhào nhiều lần bên cạnh khu green. Những đứa trẻ khác la hét vui vẻ khi tắm nước như đang nhảy múa quanh hệ thống phun nước.",
    "[324, 715, 368, 872]": "Tiểu luận\nTiểu luận A",
    "[483, 303, 563, 580]": "Một ngày nghỉ hè khi sân golf\nkhông còn là nơi chỉ dành riêng\ncho các golfer",
    "[418, 269, 687, 437]": "Các lều trại được dựng trên fairway, dán thực đơn như \"Yakisoba,\" \"Cơm cà ri,\" và \"Đá bào.\" Mùi nước sốt thơm lừng khi được nướng trên chảo gang, và bên cạnh đó, linh vật địa phương của Kanuma, \"Shikagorukun,\" đang sải bước và vẫy tay chào. \"Nóng thế này. Thời gian hoạt động tối đa của Shikagorukun chỉ được hơn chục phút thôi. Nhưng mà, năm nay lâu hơn năm ngoái nhiều rồi đấy. Nó đang cố gắng hết sức.\"",
    "[689, 269, 740, 437]": "Người không thay đổi sắc mặt khi nói là ông Sezaki Akio, Giám đốc điều hành của Kanuma 72 Country Club, nơi tổ chức \"Golf Family Festa\" lần thứ hai trong năm nay.",
    "[717, 752, 770, 921]": "Bọn trẻ không bao giờ chịu ngồi yên một giây phút nào. Ngay cả khi đi đánh cú tiếp theo trong Snag Golf, chúng cũng luôn chạy nước rút. Các nhân viên hướng dẫn cũng phải rất vất vả mới theo kịp chúng.",
    "[760, 745, 871, 937]": "so\n\"Tuy nhiên, thật là nhiều năng lượng, lũ trẻ ấy,\" ông Sezaki nhìn xa xăm. Có lẽ là vì trời nóng, hay vì ông ấy đang nhẹ nhõm khi sự kiện thành công... Lý do cho nụ cười khó tả ấy có lẽ là cả hai.",
    "[866, 68, 941, 237]": "Trên/ Fukushima Hanji, người đã vực dậy Tập đoàn Kanuma đang gặp khủng hoảng tài chính bằng tài năng của mình. Ngoài sự phong phú về ý tưởng và khả năng thực hiện, người ta còn cảm nhận được mong muốn mạnh mẽ của ông ấy là làm cho Kanuma quê hương trở nên sôi động hơn. Dưới/ Các cán bộ từ Tòa thị chính và Hiệp hội Sản phẩm Du lịch, cùng với giám đốc câu lạc bộ Golf Minami Tochigi, người đồng tình với mục đích của sự kiện này, cũng đã đến để hỗ trợ.",
    "[873, 746, 953, 937]": "Bỗng nhiên, một giọng nữ phát thanh vang lên từ chiếc loa ngoài trời đặt trên fairway. \"Bắt đầu trò đập dưa hấu.\" Tất nhiên, không ai dùng gậy golf. Lũ trẻ dùng gậy tre vung xuống. Khung cảnh đó không khác gì khung cảnh trong một \"công viên.\"",
    "[909, 262, 959, 586]": "\"Ban đầu, chính Thành phố Kanuma và Hiệp hội Sản phẩm Du lịch đã kêu gọi, và mọi chuyện bắt đầu từ cuộc thảo luận về việc liệu chúng ta có thể làm gì đó cho người dân tại sân golf hay không.\"",
    "[936, 686, 959, 699]": "*",
    "[965, 78, 980, 215]": "169 ALBA TROSS-VIEW"
  },
  "page_5": {
    "[199, 810, 521, 981]": "Người kể lại câu chuyện này là ông Fukushima Hanji, người vừa đi từ bờ hồ đến lều trại. Ông Fukushima là Chủ tịch Tập đoàn Kanuma, bao gồm Kanuma 72 Country Club, nơi tổ chức \"Golf Family Festa.\" Hiện tại, thành phố Kanuma có 13 sân golf. Đây là một trong những điểm nhấn của thành phố, đồng thời là nguồn thu nhập quan trọng từ du khách ngoài tỉnh. Tuy nhiên, liệu sân golf có gần gũi với người dân Kanuma hay không? Ông Fukushima cười gượng: \"Một bà mẹ đến đây đã nói với tôi rằng bà ấy cứ nghĩ đây là nơi không được phép vào.\" Thực tế là sân golf đã trở thành một nơi có rào cản cao. \"Bản thân các sân golf phải tìm kiếm khả năng mở rộng. Tôi nghĩ điều này cũng sẽ dẫn đến việc tăng số lượng người chơi golf.\" Điều ông Fukushima lo lắng chính là tình hình hiện tại của các sân golf ở Nhật Bản. Về cơ bản, số lượng người chơi golf và doanh số bán gậy đang giảm hàng năm, và các sân golf đóng cửa không ngừng. Mặc dù một số khảo sát cho thấy dân số chơi golf tăng lên do thế hệ bùng nổ dân số sau chiến tranh (baby boomer) sau khi nghỉ hưu có nhiều thời gian chơi hơn, nhưng hiệu ứng này được cho là sẽ giảm dần từ năm sau. Tất cả các số liệu liên quan đến golf ở Nhật Bản đều đang có xu hướng giảm. Trong bối cảnh đó, chính quyền thành phố Kanuma và các sân golf đã chia sẻ cảm giác khủng hoảng. Và Tập đoàn Kanuma—một doanh nghiệp hiếm hoi với vốn đầu tư địa phương, đã tự phục hồi sau tái cấu trúc dân sự—đang dẫn đầu nỗ lực này.",
    "[288, 226, 401, 353]": "Tiểu luận\nTiểu luận A",
    "[762, 273, 954, 432]": "... Tập đoàn đang dẫn đầu nỗ lực này. \"Rất tốt nếu có những golfer trẻ tuổi (junior) đặt mục tiêu trở thành tuyển thủ quốc tế. Nhưng những người duy trì toàn bộ ngành golf Nhật Bản lại chính là những golfer bình thường. Vì vậy, tôi mong rằng những đứa trẻ nhỏ tuổi có thể vui chơi ở sân golf như thế này, và một ngày nào đó chúng sẽ nghĩ: 'Chơi golf thử xem,' rồi bắt đầu một cách thoải mái. Dù đây là một câu chuyện cần sự kiên nhẫn và lâu dài.\" Ông Fukushima vừa lau mồ hôi vừa cười. Trước hết là làm cho người dân cảm thấy gần gũi với sân golf. Và sau đó là duy trì số lượng người chơi golf. \"Golf Family Festa\" chính là một trong những hoạt động hướng đến mục tiêu đó. Chính quyền địa phương và các sân golf đang cùng nhau nỗ lực đổ mồ hôi để đưa golf trở nên gần gũi hơn một chút.\n*",
    "[802, 608, 866, 888]": "Trước hết, hãy làm cho người ta\ncảm thấy gần gũi với sân golf,\nchứ không phải với môn golf",
    "[926, 764, 940, 777]": "*",
    "[970, 804, 983, 907]": "ALBA TROSS-VIEW 170"
  },
  "page_6": {
    "[201, 809, 447, 981]": "Một nữ nhân viên đang phụ trách trò trượt xe trượt tuyết. Trẻ em ngồi trên những chiếc xe trượt màu đỏ và trượt xuống dốc cỏ. Xe được buộc dây, và nhân viên phải dùng hết sức kéo chúng lên. Lũ trẻ thì hò reo vui vẻ, nhưng dưới cái nắng gay gắt, người nhân viên kéo dây chắc hẳn đã kiệt sức. Tuy nhiên, các nhân viên nam cũng không hề nhàn rỗi. Dưới lều, một sự kiện gọi là \"Thế giới Thủ công Vui vẻ\" đang diễn ra, nơi trẻ em tô màu lên quả thông.",
    "[483, 85, 591, 395]": "Bảo vệ truyền thống\nkhông có nghĩa là từ chối\nnhững điều mới",
    "[448, 86, 737, 255]": "Ở đây, lũ trẻ cũng rất say mê. Chúng còng lưng, tập trung ánh mắt vào một điểm và cặm cụi làm việc. Dưới bầu trời không một gợn mây của mùa hè, những quả thông được trang trí độc đáo lần lượt hoàn thành, khiến cha mẹ cũng phải mỉm cười. Tất cả nhân viên đều làm việc hiệu quả và luôn giữ nụ cười. Họ trẻ trung và rạng rỡ, khiến nơi đây trông giống một công viên giải trí hơn là một sân golf. \"Các hoạt động này được giao cho các nhân viên năm thứ hai của Tập đoàn Kanuma tự lên kế hoạch và thực hiện. Golf coi trọng truyền thống, nhưng tôi nghĩ rằng...",
    "[564, 417, 715, 786]": "\"Golf Family Festa\" được tổ chức hoàn toàn bằng công sức của nhân viên. Ngoài trải nghiệm Snag Golf đương nhiên được chuẩn bị, còn có đập dưa hấu, thổi bong bóng xà phòng, trượt xe trượt tuyết và làm thủ công, giúp những đứa trẻ hoàn toàn không hứng thú với golf cũng có thể tận hưởng. Chủ đề chính là làm cho trẻ em cảm thấy gần gũi với \"sân golf\" trước tiên, bằng cách cho chúng thỏa sức chơi đùa trên bãi cỏ mà bình thường chúng không được phép vào.",
    "[791, 747, 959, 938]": "... bảo vệ truyền thống không có nghĩa là từ chối những điều mới mẻ. Chúng tôi phải vừa giữ gìn những gì cần giữ, vừa thực hiện những điều mới. Việc giữ gìn truyền thống thì cứ để cho những người già như chúng tôi làm, còn những điều mới mẻ thì giao cho những người trẻ tuổi suy nghĩ.\" Quả thực là vậy. Ông Fukushima nhìn tôi gật gù rồi cười: \"Nhưng có lẽ họ đang tự hỏi, 'Mình đã xin vào làm ở đâu vậy? Sao lại tổ chức sự kiện tô màu quả thông dưới lều thế này?'\" Tuy nhiên, khuôn mặt của các nhân viên tại hiện trường ít nhất trông rất mãn nguyện. Và ngay bên cạnh khu vực thổi bong bóng xà phòng, cạnh nơi một cậu bé đang tập trung tô màu quả thông, có một cậu bé khoảng 5 tuổi đang thổi bong bóng theo kiểu động tác swing golf... Thật là một triển vọng tươi sáng cho tương lai! Phong trào do các sân golf ở Kanuma cùng nhau thúc đẩy này đang dần dần đơm hoa kết trái. Dù chỉ một chút, nhưng có vẻ như họ đang gieo những hạt giống chắc chắn cho tương lai. Trên thực tế, số lượng người tham dự năm nay (lần thứ hai) đã tăng từ khoảng 300 lên 350 người. Chắc chắn là người lớn mệt mỏi khi phải theo chân những đứa trẻ không biết mệt dưới cái nắng gay gắt. Nhưng nếu những nỗ lực như thế này được nhân rộng ở nhiều nơi, chẳng phải mọi thứ sẽ trở nên thú vị hơn sao? Ở đây, người lớn cũng nên lau mồ hôi và cùng chơi với bọn trẻ. Khi ra về, chắc chắn họ sẽ yêu golf hơn nữa. (Lược bỏ kính ngữ trong bài)",
    "[966, 805, 981, 942]": "171 ALBA TROSS-VIEW"
  }
}